### ISSUE TITLE
DNR: Allgemeine Sonderfertigkeiten

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#1001]
**Sources**

- S. 167 (Meteoreisen)

**Special Notes**

—

**Special Implementations**

—

**Comment by Jordok** [comment]
Hierbei handelt es sich um eine Sonderfertigkeit explizit aus dem Meister only Abschnitt von DNR. Fällt dies unter die selbe "keine Spoiler" Regelung wie Einträge aus Abenteuern oder nicht?

**Comment by elyukai** [comment]
Nein, die fällt nicht darunter, kann also eingetragen werden. Aber trotzdem gut/danke, dass du mich drauf aufmerksam machst! 😅🙈 (Bei den vielen Issues hätte ich auch gut was übersehen oder falsch eintragen können ^^)
