### ISSUE TITLE
Einhändiger Kampf

### ISSUE THREAD

**Issue by Tsafried** [elyukai/optolith-client#102]
Die Boni werden nicht auf dem Bogen übertragen. Getestet mit dem albernischen Langdolch

**Comment by elyukai** [comment]
Aktuell werden generell keine Boni von SFs etc. übertragen. Das einzige, was aktuell Einfluss auf AT/PA hat, sind die KtWs und AT/PA-Mods. :( Das kommt aber mit #59! 🎉
