### ISSUE TITLE
DNRX: Erweiterte Talentsonderfertigkeiten

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#1027]
**Sources**

- S. 11–12 (Erweiterte Talentsonderfertigkeiten)

**Special Notes**

—

**Special Implementations**

—

**Comment by panikpansen** [comment]
Alle in diesem Band enthaltenen erweiterten Talentsonderfertigkeiten sind bereits in der SpecialAbilities.yaml aufgelistet, mit ids SA_1096, SA_1103, SA_1108, SA_1112, SA_1114, SA_1128 respektive. Jeweils inhaltsgleich mit Ausnahme von SA_1114 ("Kunstbegabt"), wo in der vorhandenen Version ein kleiner typo drin ist, der in GMH-DNRX:12 behoben ist. Den Typo fix habe ich als https://github.com/elyukai/optolith-data/commit/3416f8435e61105ff6ff076580169708bb450870 submitted.
