### ISSUE TITLE
DDD: Animistenkräfte

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#1058]
**Sources**

- S. 151–152 (Animisten)

**Special Notes**

—

**Special Implementations**

—

**Comment by panikpansen** [comment]
Die in DDD 151-152 aufgeführten Animistenkräfte füge ich in einem neuen Branch in die AnimistForces.yaml ein. Nur um sicher zu gehen: die in DDD 150-151 aufgeführten Patrone (von denen noch nicht alle in der Patrons.yaml zu finden sind) sind aber von dieser Issue nicht erfasst, oder?
