### ISSUE TITLE
SKR/SWK/HAV/FLU: Wesenszüge

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#1075]
**Sources**

- S. 154–156 (SKR: Wesenszüge)
- S. 154–155 (SWK: Wesenszüge)
- S. 82–83 (HAV: Wesenszüge)
- S. 148–150 (FLU: Wesenszüge)

**Special Notes**

—

**Special Implementations**

—

**Comment by pickbreaker** [comment]
Implemented. Waiting for completion of #1056, #1076 and #1079 before sending PR
