### ISSUE TITLE
Wrong page number in description of Albernisches Entermesser and Harbener Säbel

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#1081]
**Source (please complete the following information):**

- Book: Rüstkammer der Siebenwindküste
- Printing: 1st
- Page(s): 9
- Area: Albernisches Entermesser, Harbener Säbel

**Describe the bug**

> Das Albernische Entermesser kann nicht zweihändig geführt werden (siehe Regelwerk Seite 266).
> 
> Das müsste Seite 366 sein, richtig?
> Desgleichen beim Harbener Säbel

— **Madayar** on Discord

**Expected text**

X kann nicht zweihändig geführt werden (siehe Regelwerk Seite 366).

**Optolith Version:**

—

**Additional context**
If needed, add any other context about the problem here.

**Comment by Pepelios** [comment]
Fix will be part of branch "Fix typo in page size description"
