### ISSUE TITLE
Race prerequisite does not display race required

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#1093]
> Beim Cendrasch-Stil wird im Wiki-Tab bei Voraussetzungen nicht Spezies: Zwerg, sondern nur Spezies angegeben

— **Tengwean** on Discord

> glaub bei anderen auch (Balboram iirc)

— **Atagon** on Discord

> auch bei den elfenstilen

— **Xardai** on Discord

**Comment by Pepelios** [comment]
Scheint ein generelles Issue zu sein. Alle Zwergen und Elfenspezifischen Stile sind betroffen.

**Comment by Pepelios** [comment]
Scheinbar sind auch SFs betroffen.

**Comment by Pepelios** [comment]
Fixed.
