### ISSUE TITLE
Typo in cantrip Hintergrundmusik effect text

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#1110]
> Das Stück kann der Zauberer selbst **bestimmten**, es muss aber zum Ambiente passen.

should be

> Das Stück kann der Zauberer selbst **bestimmen**, es muss aber zum Ambiente passen.

(changed words are marked bold).

**Comment by Pepelios** [comment]
Typo war in File Cantrips.yaml Habe ihn gefixt und committed.

**Comment by elyukai** [comment]
Ist bei Ulisses noch falsch.
