### ISSUE TITLE
Typo in Gespür für Himmelsrichtungen

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#1111]
> Mithilfe

should be 

> Mithilfe

(or the other way around).

**Comment by Pepelios** [comment]
Dieser Typo ist in Beeren & Nüsse, Wasserlauf, Kristallzucht, Routinierte Zauberwiederholung, Schnelles Brauen, Gespür für Himmelsrichtungen, Herzschlag ruhe und Infinitum Immerdar.

Ist "Mithilfe" nun korrekt oder "Mit Hilfe"?  Beides kommt in zig Publikationen vor.

**Comment by elyukai** [comment]
Okay, also ich hab eben mal in den Duden geschaut. Tatsächlich geht beides, auch wenn "mithilfe" empfohlen ist. Ist also gar kein Fehler … 🥶 Ich werde den dann mal schließen, sorry, daran hatte ich gar nicht gedacht zu dem Zeitpunkt … 🙈
