### ISSUE TITLE
AMAII: Ritual Zauberschnurren: Fehler in der Wirkungsbeschreibung

### ISSUE THREAD

**Issue by Medsmiley** [elyukai/optolith-client#1122]
- Book: Aventurische Magie II
- Printing: 2. Auflage
- Page(s): 138
- Area: Ritual Zauberschnurren, Wirkung

**Describe the bug**
Unter der Wirkung des Rituals wird nach der Beschreibung von QS1 zuerst QS3 und anschließend QS2, gefolgt von QS4 beschrieben. 
![grafik](https://user-images.githubusercontent.com/49515328/111851536-da9c6a80-8913-11eb-9b4b-cbf22e15d1bf.png)

**Expected text**
Anstatt obiges sollte dort die korrekte Reihenfolge QS1-6 stehen. Logisch wäre, dass es ein Tippfehler ist und die Zahlen 2&3 vertauscht wurden. Andernfalls müsste die Reihenfolge beider Sätze getauscht werden.

**Optolith Version:**
In der Optolith Datenbank ist der Fehler exakt gleich, da übernommen aus dem Werk (gerade 1.4.2).

**Comment by Pepelios** [comment]
Ich habe mal an Ulisses geschrieben, um eine Antwort der Redax zu erhalten, was nun richtig ist.
Im Wiki und sonstwo ist der Fehler auch überall.

**Comment by Pepelios** [comment]
Hallo Kai,

 

es sind nur die QS-Nummern vertauscht, die Wirkung ist jedoch von der Reihenfolge her korrekt.

 

Liebe Grüße,

deine DSA-Redaktion

 

Ulisses Medien & Spiel Distribution GmbH
Industriestr. 11
65529 Waldems Steinfischbach

Telefon: +49-(0)6087-98870-0

Fax: +49-(0)6087-98870-599
eMail: feedback@ulisses-spiele.de

Internet: www.ulisses-spiele.de
 

Gerichtsstand: Wiesbaden 25 HRB 13183
UstlDN: DE 186 482 357
Geschäftsführer: Markus Plötz

**Comment by Pepelios** [comment]
Fixed
