### ISSUE TITLE
Wirbelform unclear

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#1139]
## Source (please complete the following information):

- Book: Aventurische Magie II
- Printing: 1st
- Page(s): 137
- Area: Wirbelform

## Describe the bug

Wirbelform existiert hier als Ritual der Tradition Elfen und Größerer Radius als erste Zaubererweiterung. In AMA1 153 steht das Ritual mit der Tradition allgemein und Längere Wirkungsdauer 1 als erste Zaubererweiterung. Ferner ist Wirbelform in AMA2 162–163 als Zauberspruch in elfischer Tradition, als Ritual in allgemeiner Tradition (mit Verweis auf AMA1) sowie als RItual in elfischer Tradition gelistet. Letzteres wäre ja am sinnvollsten, aber …?

## Optolith Version:

1.4.2

## Additional context

—

**Comment by Pepelios** [comment]
Die Version aus AMA II ist die richtige. 
Es müssten aber die Zaubererweiterungen korrigiert werden, da hier die Reihenfolge und Werte nicht stimmen.

Zaubererweiterungen:
• Größerer Radius (FW 8, 2 AP): Der Radius beträgt QS
x 2 Schritt.
• Längere Wirkungsdauer 1 (FW 12, 4 AP): Die Wirkungsdauer
beträgt QS x 30 Minuten.
• Längere Wirkungsdauer 2 (FW 16, 6 AP): Die Wirkungsdauer
beträgt QS Stunden. Voraussetzung: Zaubererweiterung
Längere Wirkungsdauer 1.

**Comment by elyukai** [comment]
Did you request an official statement from Ulisses?

**Comment by Pepelios** [comment]
I request an official statement.  I just fixed it like it was in AMA II.

**Comment by Pepelios** [comment]
DSA Redaktion sagt, dass Wirbelform von AMA II korrekt ist. Damit sollten meine Codeänderungen so nun auch stimmen.

**Comment by Pepelios** [comment]
Da in der RSH Thorwal der Zauber wieder mit der Verbreitung "Allgemein" steht, anstatt wie in AMA II mit "Elfen", habe ich nochmal die DSA Redaktion befragt.  Antwort ist sinngemäß: "Sie denken dass das in RSH Thorwal ein Fehler ist, Verbreitung Elfen sollte es sein, aber sie prüfen es nochmal für eine Errata".

-----
Zitat Alex: "dies sieht mir eher wie ein Fehler in der Thorwal-RSH aus, vermutlich wurde einfach nur die erste Version übernommen. Zwar wäre es dann entsprechend ein Zauber der Verbreitung Elfen, dennoch kann ein Thorwaler Gildenmagier den Zauber ja aktivieren. Wir prüfen das auf jeden Fall nochmal und notieren ggf. eine Errata."

**Comment by elyukai** [comment]
Hier nun auch sehr verspätet nochmal die Antwort von Alex auf meine damalige Nachfrage.

Mein Text:

> Wirbelform existiert in AMA2 als Ritual der Tradition Elfen und Größerer Radius als erste Zaubererweiterung. In AMA1 steht das Ritual mit der Tradition allgemein und Längere Wirkungsdauer 1 als erste Zaubererweiterung. Ferner ist Wirbelform in der Zauberübersicht in AMA2 als Zauberspruch in elfischer Tradition, als Ritual in allgemeiner Tradition (mit Verweis auf AMA1) sowie als RItual in elfischer Tradition gelistet. Letzteres wäre ja am sinnvollsten, da alle anderen …form-Rituale auch Verbreitung Elfen haben, aber was genau gilt hier?

Antwort:

> ja, letztes ist korrekt.

— Alex Spohr, DSA-Redaktion
