### ISSUE TITLE
Catch Blade: MeeleCombatTechniques

### ISSUE THREAD

**Issue by Lhiuvian** [elyukai/optolith-client#1157]
src 1

- GRW 
- 4. Auflage
- S.248
- alle Parierwaffen unter Kampftechniken angeführt und im Optolith ist es unter "Dolche" angegeben

welche Kampftechniken fallen alle unter "alle Parierwaffen"? @elyukai

**Comment by elyukai** [comment]
Es geht hier einfach darum, dass es nur für Parierwaffen gilt. Also keine bestimmten Kampftechniken, eher die Waffenart.

**Comment by elyukai** [comment]
Bisher ließ sich das auch noch nicht abbilden. Mittlerweile geht das in der neuen Datenbank und sollte auch so eingetragen sein.
