### ISSUE TITLE
Skill Style Special Ability "Weg des Holzfällers" requires advantage Spellcaster

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#119]
**Describe the bug**
Skill Style Special Ability "Weg des Holzfällers" requires advantage Spellcaster.

**Expected behavior**
No such prerequisite.

**Environment**
 - OS: Windows 10
 - Version 1.2.0-alpha.1

**Comment by LLmichi1** [comment]
Changed Prerequisite to "Holzbearbeitung 8" as expected
