### ISSUE TITLE
Typo in german "Invocatio Minima" description

### ISSUE THREAD

**Issue by 0xE282B0** [elyukai/optolith-client#1224]
## Source (please complete the following information):

https://ulisses-regelwiki.de/zauber.html?zauber=Invocatio+Minima
- Regelwerk, Seite 293
- **Aventurische Magie, Seite 158**

## Describe the bug

The text of the Spell "Invocatio Minima" in german language says in the spell extension 
- `Größere Menge (FW 8, 1 AP): Die Menge der dämonischen Essenz steigt auf 1 l pro QS.`
- `[...] Essenz steigt auf 2 l pro QS. [...]`
- `[...] Essenz steigt auf 4 l pro QS. [...]`

Where the Wiki says 0.1l, 0.2l, & 0.4l instead of 1l, 2l & 4l.

## Expected text

- `Größere Menge (FW 8, 1 AP): Die Menge der dämonischen Essenz steigt auf 0,1 l pro QS.`
- `[...] Essenz steigt auf 0,2 l pro QS. [...]`
- `[...] Essenz steigt auf 0,4 l pro QS. [...]`

## Optolith Version:
Optolith 1.4.2

**Comment by elyukai** [comment]
Thanks for the report! 🥰

Do the books say "0,X" instead of "X" as well?

**Comment by 0xE282B0** [comment]
Yes, **Aventurische Magie, Seite 158** says 0,X l for Invocatio Minima.

**Comment by elyukai** [comment]
Thanks for looking up! 🥰
