### ISSUE TITLE
Skill Style SA Weg der Schreiberin not available even with matched prerequisites

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#1233]
## Describe the bug

Ich hab ne kurze Frage zu dem Talenstil Weg der Schreiberin. Da ist doch die einzige Voraussetzung, dass man eine Sprache und dazugehörige Schrift hat oder? Denn ich find den zwar im Wiki in Optolith, allerdings wird der mir nicht auf meinen Helden angeboten, obwohl ich jeweils Garethi III und Kusliker zeichen habe

— **WizardNemo** on Discord

## To Reproduce

1. Buy Language
2. Buy script
3. Still don't see the SA

## Expected behavior

I can buy the SA "Weg der Schreiberin"

## Screenshots

![grafik](https://user-images.githubusercontent.com/11094577/116787099-7c31e280-aaa2-11eb-9e75-9a88ca31ba3f.png)

## Environment

- OS: Windows 10
- Version: 1.4.2

## Additional context

—

**Comment by Jordok** [comment]
Hab auf die schnelle drüber gschaut, muss was tieferliegendes sein, da die Vorraussetzungen eigentlich drinnen stehen.

`- id: SA_1075
# name: Weg der Schreiberin
  cost: 5
  max: 1
  extended:
    - SA_1094
    - SA_1111
    - SA_1120
  activatablePrerequisites:
    - id: SA_27
      active: true
    - id: SA_29
      active: true
  gr: 33`
  
 Das ist konkret die besagte SA, SA_27 ist Schrift, SA_29 ist Sprache. Könnte sein das es mit 2.0.0 durch das neue Schema wieder geht, ist also fraglich ob konkrete Fixes vorher den Zeitaufwand wert sind (wie von WizardNemo selbst geschrieben, diese SF wird seltenst genutzt).
