### ISSUE TITLE
"Vorliebe (Sexpraktik)" (advantage) name contains levels

### ISSUE THREAD

**Issue by BlueSkyBlackBird** [elyukai/optolith-client#1242]
**Describe the bug**
The advantage Vorliebe (Sexpraktik) has the suffix "I-II" in the name which is an inconsistency.

**To Reproduce**
Look at the latest version of data on DEV.

**Expected behavior**
```
- id: ADV_118
  name: "Vorliebe (Sexpraktik)"
```

**Screenshots**
```
- id: ADV_118
  name: "Vorliebe (Sexpraktik) I-II"
```

**Environment (please complete the following information):**
irrelevant

**Additional context**
none

**Comment by elyukai** [comment]
It's already fixed in the new database, but I'll see if I can change this in the old database as well if I have some spare time (this issue occurs at several entries from WDV)! 😬 Thanks for the report! :3
