### ISSUE TITLE
Border around the picture on the pdf not continuous

### ISSUE THREAD

**Issue by Saphirius** [elyukai/optolith-client#1245]
**Describe the bug**
If u choose a picture, on the pdf a border is shown on every side, except on the right.

**To Reproduce**
Add a picture and download the pdf

**Expected behavior**
Should be no border, or border all-around.

- OS: Windows 10
- Version: 1.4.2 and 1.4.3-alpha.1]

**Comment by elyukai** [comment]
This was a result of some wrong styling. Fixed with #800. Thanks for the report! :3 👍🏻
