### ISSUE TITLE
SF Magische Regeneration I-II Vorrausetzung wird nicht beachtet

### ISSUE THREAD

**Issue by RondraLion** [elyukai/optolith-client#1260]
- OS:  Windows 10
- Version: 1.5.0-alpha.2

Hallo mir ist gerade aufgefallen, das man die KL unter 15 senken kann obwohl man die SF Magische Regeneration hat. Die Vorrausetzung ist hier Leiteigenschaft 15.

**Comment by elyukai** [comment]
Hi!

Könntest du evtl. die Umgebungsinformationen des [Issue Templates](https://github.com/elyukai/optolith-client/issues/new?assignees=&labels=Bug&template=bug_report.md&title=) einmal ausfüllen? Sind auch hier einmal direkt:

```md
- OS: [e.g. Windows 10]
- Version: [e.g. 1.1.0, 1.3.0-alpha.5]
```

Dann weiß ich wo ich suchen muss. Danke! :)

**Comment by RondraLion** [comment]
Ist gemacht

**Comment by RondraLion** [comment]
Sry jetzt ist es richtig ^^

**Comment by elyukai** [comment]
Alles gut, danke! ^^ Ich war schon kurz davor zu fragen, ob du das mit der neuesten auch verifzieren kannst, aber das hat sich damit ja erledigt! XD

**Comment by Jordok** [comment]
OS: Linux (Lubuntu)
Version: 1.5.0 - Alpha.4
reproduzierbar, es scheint sich um ein Problem beim speicher/neu laden des Charakters zu handeln. Direkt nach auswählen der SF ist die Leiteigenschaft nicht unter 15 reduzierbar, nach dem speichern, schließen und neu öffnen des Opto jedoch schon.
