### ISSUE TITLE
Schwertgesellen (z.B. Fedorino) sind bei durchschnittlichen Helden nicht auswählbar 1.5.0-alpha.4

### ISSUE THREAD

**Issue by LordNeilo** [elyukai/optolith-client#1319]
## Describe the bug

Einige Professionen (getestet mit Fedorino-Schwertgeselle) sind bei einem Durchschnittlichen (1000AP) Helden in der 1.50.-alpha.4 nicht auswählbar, sehr wohl aber mit einem 1100AP Helden. In der Aktuellen Releaseversion sind die Professionen passend auswählbar.

## To Reproduce

1. Go to 'Neuer Held' 'Erfahrungsgrad Durchschnittlich' 'Kompendium I (oder Alle Regelwerke)'
2. Click on 'Mensch, Mittelländer, Mittelreicher oder Horasier,'
3. Scroll down to 'Fedorino-Schwertgeselle'
4. See missing entry.

## Expected behavior

Die Profession muss auswählbar sein. Dies ist in der aktuellen Releaseversion so. 

## Screenshots
![Bildschirmfoto 2021-09-13 um 12 38 13](https://user-images.githubusercontent.com/34488783/133069616-91c70ee2-6e44-43ec-930e-ef8de161cae7.png)

## Environment

Please complete the following information:

- OS: macOS Monterey Version 12.0 Beta
- Version: 1.5.0-alpha.4

**Comment by Jordok** [comment]
Soweit ich das sagen kann handelt es sich hier im keinen Fehler, sondern um ein beabsichtigtes Ausblenden von nicht wählbaren Professionen. Besagter Schwertgeselle würde mit Fechtwaffen 12 starten, laut Regelwerk S.39 ist das Maximum einer Fertigkeit 10, wenn man den Erfahrungsgrad "durchschnittlich" nimmt.
in dem Fall also tatsächlich: it's not a bug, it's a feature ;-)

**Comment by elyukai** [comment]
Das ist richtig, das Ausblenden ist erst "kürzlich" hinzugekommen, als ich festgestellt hatte, dass ich das noch nicht abprüfe und anders als bei Talenten der maximale Wert durch den EG bei KAmpftechniken unter den Wert bei *Erfahren* sinken kann.
