### ISSUE TITLE
Trade Secrets missing

### ISSUE THREAD

**Issue by Tandosch** [elyukai/optolith-client#1326]
## Describe the bug

The Trade Secrets "Schmerzwein" and "Schlaftrunk" are missing

## To Reproduce

1. Open Char
2. Click on Abilities
3. Click on Special Abilities
4. Enshure that Trade Secret: "Schmerzwein" and "Schlaftrunk" are not shown in the list of choosen Spcial Abilities
5. Click on "Add"
6. Select Trade Secret "Schmerzwein" and "Schlaftrunk"

## Expected behavior

Trade Secrets can be choosen, because there are no preconditions

## Environment

Please complete the following information:

- OS: Windows 10
- Version: 1.5.0-alpha.5]

**Comment by elyukai** [comment]
Are you missing the ones from the Aventuria Herbary?

**Comment by elyukai** [comment]
Since I assume this is from the Herbary, which is not yet available but tracked in #526 and sub-issues, I'm gonna close this one, please reopen if my assumption is incorrect!
