### ISSUE TITLE
Rogue not available in ordinary exerience level

### ISSUE THREAD

**Issue by Tandosch** [elyukai/optolith-client#1347]
## Describe the bug

The proffesion "Rougue" is not availabe with Experience Level "Ordinary"

## To Reproduce

1. Go to 'New Hero'
2. Select Name/sex/all rules
3. Select experience Level "Ordinary"
4. click "Go"
5. Select Race Humans/Middenrealmers
6. Select Culture Middenrealmer
7. Select Profession "Rouge" 

## Expected behavior
Rogue is available

## Environment
Please complete the following information:

- OS: [e.g. Windows 10]
- Version: [current (05.02.22)]

## Additional context
With experience Level "Experienced" the profession Rouge is available

**Comment by elyukai** [comment]
Thank you for your issue! 🙏🏻

It's not available because it gives you a *Combat Technique Rating* of 12, which is not allowed on *Ordinary*. Only 10 is allowed there.
