### ISSUE TITLE
Kann "Licht des Madamals" nicht finden/auswählen.

### ISSUE THREAD

**Issue by milkpirate** [elyukai/optolith-client#1359]
### Please confirm the following

- [X] I checked the [current issues](https://github.com/elyukai/optolith-client/issues) for duplicate problems.

### Describe the bug

Siehe Titel.
![image](https://user-images.githubusercontent.com/9251021/158073408-f7ce16db-423e-4a51-b42e-afc10e387dd3.png)

### To Reproduce
Alle Regelwerke:
![image](https://user-images.githubusercontent.com/9251021/158074035-b31bd324-e03e-4905-89aa-810672ef9fd4.png)

Besitze das Mondamulett:
![image](https://user-images.githubusercontent.com/9251021/158073497-78cd7fb4-1f68-44c8-8db5-05a78dce7a83.png)

Tradition verfügbar:
![image](https://user-images.githubusercontent.com/9251021/158073524-23a93d9b-1a0a-4700-9a3d-7a843b07e90f.png)

Kein "Gespür für Geld"
![image](https://user-images.githubusercontent.com/9251021/158073456-5613e174-4c12-48b5-ba96-18ad5735980e.png)

**aber KEIN** "Licht des Madamals"
![image](https://user-images.githubusercontent.com/9251021/158073589-6aebeb1c-f194-49c5-aa6b-5d9b68da3b9c.png)

### Expected behavior

Dass hier etwas gefunden wird:
![image](https://user-images.githubusercontent.com/9251021/158073643-361d8ead-6b60-4e4a-8c96-e7d84dc57bfc.png)

### Screenshots

Siehe oben.

### Operating System

Windows

### Version

1.5.0

**Comment by milkpirate** [comment]
@elyukai could you have a look on that?

**Comment by milkpirate** [comment]
Thanks so much!

**Comment by elyukai** [comment]
You're welcome! 🙌🏻 Sorry again for my late reply … 🙈🙈
