### ISSUE TITLE
Bei Auswahl mehrerer Nachteile ist die AP-Modifikation fehlerhaft

### ISSUE THREAD

**Issue by Brausepaul** [elyukai/optolith-client#1378]
### Please confirm the following

- [X] I checked the [current issues](https://github.com/elyukai/optolith-client/issues) for duplicate problems.

### Describe the bug

Bei Auswahl mehrerer Prinzipientreue-Nachteile unterschiedlicher Stufe ist die Berechnung der AP-Modifikation falsch, es wird ggf. zu wenig gutgeschrieben.

### To Reproduce

1. Gehe zum Dialog Nachteile
2. Füge einmal Prinzipientreue auf Stufe I hinzu
3. Füge einmal Prinzipientreue auf Stufe II hinzu.

Es erfolgt AP 0 für Stufe I und AP -10 für Stufe II.

### Expected behavior

AP 0 für Stufe I und AP -20 für Stufe II

### Screenshots

![Screenshot 2022-06-13 133522](https://user-images.githubusercontent.com/13948653/173345116-8878250c-1f62-4112-88c4-4d76df33e122.png)

### Operating System

Windows

### Version

1.5.1

**Comment by elyukai** [comment]
Vielen Dank für den Report!

Das Verhalten ist aber tatsächlich so gewollt. Leider ist es schwierig, ein in allen Situationen nachvollziehbares System zu entwickeln, daher sind die Kosten, die direkt bei V/N/SF stehen, die, die beim Hinzufügen bzw. Entfernen dieses Eintrags entstehen. In diesem Fall also: Entfernst du die PT auf Stufe I, werden deine ausgegebenen AP nicht verändert, wenn du die auf Stufe II entfernst, verlierst du 10 AP und bei der auf Stufe I steht dann –10 AP. Die Gesamtkostenrechnung ist aber trotzdem korrekt, da dafür vorher noch entsprechende Modifikationen durchgeführt werden, damit der absolute Wert am Ende richtig ist.

Das von dir erwartete Verhalten birgt leider den Nachteil, dass es unvorhersehbarer im Bezug auf das Hinzufügen und Entfernen ist.

Beispiel:

Du hast zwei Prinzipientreuen auf Stufe I. Wenn die *Summe* korrekt sein soll, muss ein Eintrag dann –10 AP zeigen und einer 0 AP. Wenn du dann den Eintrag mit –10 AP entfernst, verlierst du keine AP, weil ja noch der andere Eintrag da ist, der nach dem Entfernen dann –10 AP anzeigt und du die dann ja auch tatsächlich verlierst, wenn du den Eintrag wieder entfernst.

Ich habe leider noch keine Lösung für das Problem, welches alle Missverständnisse ausräumen kann. Und leider auch noch keine Zeit gehabt, mir intensiv dazu Gedanken zu machen.

Dazu auch: #372

Da ein UX-Issue dazu schon existiert, markiere ich den Issue hier mal als Working as intended.
