### ISSUE TITLE
Glaube, Macht & Heldenmut: Die Streitenden Königreiche

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#148]
**Sources**
Sonderfertigkeiten S.14
Profession Seite 5 (Ritter der Streitenden Königreiche)

Rest scheint alles Dopplung zu sein und benötigt nur Quellangabe:
Professionen Seite 5-11
Sonderfertigkeiten Seite 14-18

**Tables**
- [x] Univ
- [x] L10n de-DE

**Comment by Jordok** [comment]
in 2.0.0 überprüft, bis auf das Ding mit den Professionen ist hiervon alles erledigt.

> Potential Issue in 2.0: the Professions out of SKRX mostly don't have their own instanz for SKRX, and it would have to be added between their Instanz 1 and 2. (SKRX S. 5-11).
