### ISSUE TITLE
WdV: Disadvantages

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#152]
**Quelle:** S. 151-154

**Tables**
- [x] Univ
- [x] L10n de-DE
- [x] Impotent und Unfruchtbar alphabetisch einsortieren

**Comment by Alberix89** [comment]
Bei Abneigung braucht es noch eine weitere Angabe. Entweder eine Auswahl der möglichen Abneigungen oder ein Eingabefeld (man kann ja max. 2 Abneigungen wählen).

**Comment by elyukai** [comment]
Abneigung ist ja quasi das Gegenstück zum Vorteil Vorliebe, richtig? Dafür hab ich bereits in der neuen Datenbank eine Liste der Sexpraktiken angelegt, sodass ich diese dann für Vorliebe und Abneigung übernehmen kann. 👍🏻 Aber an Abneigungen hatte ich dabei gar nicht gedacht! 😬 Danke! 🙈

**Comment by elyukai** [comment]
Ich habe die Liste in #463 verschoben, um dort die Übersicht zu haben. Ansonsten passt hier alles.

**Comment by elyukai** [comment]
Doch, aber sie wurden nachträglich hinzugefügt, weil ich sie vergessen hatte. Die WDV-Nachteile sind nicht richtig sortiert. Sieht man auch schon, wenn man die Quellenangaben von 80 und 81 vergleicht. Das müsste in eine richtige Reihenfolge gebracht werden, damit keine Verwirrung entsteht. Allerdings müssen auch **alle Voraussetzungen** durchgesehen werden, die die Nachteile, die dadurch eine andere Reihenfolge bekommen, referenzieren, da sich dann ja auch die IDs ändern.
