### ISSUE TITLE
AP für Verpflichtung werden nicht korrekt angezeigt

### ISSUE THREAD

**Issue by Kallimeister** [elyukai/optolith-client#1593]
### Please confirm the following

- [X] I checked the [current issues](https://github.com/elyukai/optolith-client/issues) for duplicate problems.

### Describe the bug

Bei einer Verpflichtung werden im Nachteilereiter die -10 AP für diese korrekt angezeigt: Beim Hinzufügen einer zweiten Verpflichtung werden danach allerdings beide mit 0 AP angezeigt. (Die zweite kostet ja laut Regeln 0 AP, es werden auch keine Kosten berechnet)
Ändert man bei der Zweiten beim Hinzufügen die AP manuell auf z.B. -10 werden im Übersichtsreiter nur bei dieser die -10 angezeigt, bei der ersten jedoch auch 0, ob wohl diese mit -10 in die Gesamt-AP-Berechnung zählen.

### To Reproduce

Siehe Beschreibung

### Expected behavior

Siehe Beschreibung

### Operating System

Windows

### Version

Insider 1.5.1

**Comment by elyukai** [comment]
Die AP-Anzeige ist nicht die Anzeige der dafür investierten AP, sondern der AP, die man bei einem Rückkauf erhalten würde. Ich verweise mal auf andere Issues für ausführliche Erläuterungen: #1378, #372
