### ISSUE TITLE
Bad Luck starts with 3 FtP on the character sheet

### ISSUE THREAD

**Issue by Wujekklawy** [elyukai/optolith-client#1607]
### Please confirm the following

- [X] I checked the [current issues](https://github.com/elyukai/optolith-client/issues) for duplicate problems.

### Describe the bug

When getting Bad Luck (The hero **starts the game with one less FtP per level of this disadvantage**. The hero’s maximum number of FtP drops, too, by one point per level of this disadvantage. The hero’s total number of FtP cannot be reduced below 0.), on the character sheet Value is at 3 instead lowered one, max one is fine

### To Reproduce

1. take Bad Luck
2. end hero creation
3. check character sheet

### Expected behavior

Bad Luck I should start with 2 FtP, Bad Luck II with 1 FtP.

### Screenshots

![Bez nazwy](https://github.com/elyukai/optolith-client/assets/25621896/38806eef-3fba-48c2-9cd7-6ea048dbbf2f)

### Operating System

Windows

### Version

1.5.1

**Comment by elyukai** [comment]
Thank you for your bug report. I'm not quite sure what you mean, though. The base value is 3. You have Bad Luck II which makes a modifier of –2 applied to the base value. And this results in a maximum value of 1. This is also what's on the screenshot. So to me this looks like it's working as expected/intended. What do I miss? 🙈

**Comment by Wujekklawy** [comment]
it also modifies starting value not only max value but also decreases amount you start with, at least it suposed to, oh, w8 current are next to it 😅

**Comment by elyukai** [comment]
Well it also implicitly decreases the starting value since you can't have more than that.

**Comment by Wujekklawy** [comment]
i read character sheet wrong, assumed "value" is a current value
