### ISSUE TITLE
Kodex der Helden: Tulamidischer Balayan missing

### ISSUE THREAD

**Issue by Pu5chk1n** [elyukai/optolith-client#1615]
## Sources

> Aus "Kodex der Helden" das Professionspaket "Tulamidischer Balayan" sowie die Varianten fehlen vollständig.

Kodex der Helden
> - S. 196 Professionspaket "Tulamidischer Balayan"

**Comment by elyukai** [comment]
Danke für den Report. Generell fehlen alle Kodizes und Archive, da es leider sehr aufwändig ist, alles nach Änderungen zu überprüfen und keine Änderungslisten existieren, nach denen man die aktuell in Optolith enthaltenen Einträge recht schnell aktualisieren könnte.

Daher wird dieser Issue bereits von #1599 abgedeckt.
