### ISSUE TITLE
Posibility to check locked special abilities

### ISSUE THREAD

**Issue by Wujekklawy** [elyukai/optolith-client#1627]
## Is your feature request related to a problem?

Sometimes when creating a character or just evolving one you need to check books often for special abilities you want to get and then compare the prerequisites for them

## Describe the solution you'd like

toggleable option that shows special abilities that are not shown and to see why they are not shown (missing attribute, not enough skill value etc.)

## Describe alternatives

adding in the info tab prerequisites instead of showing it separately

**Comment by elyukai** [comment]
Thanks for your feature request! ❤️

I sadly have to say, though, that this issue already exists as #27, so I'm gonna close this as a duplicate.
