### ISSUE TITLE
Impossible to download this anywhere....

### ISSUE THREAD

**Issue by Nymra** [elyukai/optolith-client#1631]
### Please confirm the following

- [X] I checked the [current issues](https://github.com/elyukai/optolith-client/issues) for duplicate problems.

### Describe the bug

What is this? There is no working link, no way to download this anywhere.
Its 2024 and it is impossible for you to provide a SIMPLE direct download link on the website?

### To Reproduce

What is this? There is no working link, no way to download this anywhere.
Its 2024 and it is impossible for you to provide a SIMPLE direct download link on the website?

### Expected behavior

What is this? There is no working link, no way to download this anywhere.
Its 2024 and it is impossible for you to provide a SIMPLE direct download link on the website?

### Screenshots

What is this? There is no working link, no way to download this anywhere.
Its 2024 and it is impossible for you to provide a SIMPLE direct download link on the website?

### Operating System

Windows

### Version

111

### Additional context

What is this? There is no working link, no way to download this anywhere.
Its 2024 and it is impossible for you to provide a SIMPLE direct download link on the website?

**Comment by pickbreaker** [comment]
Due to licensing by Ulisses Spiele this software can only be sourced through their site. Please download it here: https://www.ulisses-ebooks.de/product/209711/Optolith-Heldenverwaltung or here: https://www.drivethrurpg.com/en/product/220253/optolith-character-generator as stated in the README file.
