### ISSUE TITLE
AMA3-Errata: Zaubertricks

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#174]
**Sources**
AMAIII Bonusmaterial
Seite 7-8

**Tables**
- [x] Univ
- [x] L10n de-DE
- [x] Review

**Comment by JoveToo** [comment]
CANTRIP_93 (Feuerspiel) has tradition 1, which is not in the Traditions file.
Should be Anmerkung: Gildenmagier (Halib abu’l Ketab)
