### ISSUE TITLE
Einige Zauber des Scharlatans listen diesen nicht als Tradition

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#197]
Die Zauber "Oculus" und "Duplicatus" werden beim Scharlatan in der aktuellen Softwareversion (1.1.2) als Fremdzauber geführt. Im Regelwiki werden sie aber beide unter "Vebreitung: Gildenmagier, Scharlatane" gelistet.

**Comment by Jordok** [comment]
Scheint in 1.2.0 Alpha 4 behoben zu sein
