### ISSUE TITLE
Rüstkammer der Flusslande: Ausrüstung

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#210]
## Sources

- [x] S. 5–12 (Waffen)
- [x] S. 13–14 (Rüstzeug)
- [x] S. 15–19 (Zwergisches Arsenal)
- [x] S. 20–21 (Werkzeuge und Improvisierte Waffen)
- [x] S. 22–23 (Besondere Gegenstände)
- [x] S. 33 (Warenliste)

**Comment by Jordok** [comment]
Haben sich beim eintragen 2 Probleme ergeben.
1) Die speziellen Gegenstandseigenschaften (note, advantage, disadvantage) wurden so eingetragen als ob sie im "Die Flusslande" stehen würden, was sie nicht tun. Korrigieren oder ignorieren?
2) Der hier vorhandene Ingerimmshammer hat andere andere Werte als der aus AGÖI, (PA-Mod von -1 statt -2). Soll der RÜFLU Ingerimmshammer als neuer Gegenstand ins System, oder der AGÖI Hammer verändert werden?
