### ISSUE TITLE
Bad Luck I-III do not reduce FtP on the character sheet

### ISSUE THREAD

**Issue by ZeSandman** [elyukai/optolith-client#219]
**Describe the bug**
Character created with the Disadventage Bad Luck always have 3 Fate Pts on the generated Character Sheet

**To Reproduce**
Create Character with Bad Luck Disad, End Char Chreation, Look at generated Charsheet.  Same behaviour for the PDF export so it's not just a display problem

**Expected behavior**
Bad Luck should reduce the Fate Pts of the character by 1 for each level

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/55366389/65749610-6a24dc80-e0d4-11e9-8baf-671cdc442738.png)

**Environment**
 Linux AppImage
Version 1.1.2

Test Character
[TDE_25001_64_Korgrimm.zip](https://github.com/elyukai/optolith-client/files/3661326/TDE_25001_64_Korgrimm.zip)

**Comment by ZeSandman** [comment]
Seems top be fixed in the Insider version.

**Comment by lathspell** [comment]
In case somebody else stumbles over this bug: The opposide effect, "Luck I-III" also did not increase FtP. This, too, is fixed in the latest Insider release 1.2.0.alpha6.
