### ISSUE TITLE
Saving heroes does not always clear past history

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#239]
> wenn ich mehrere Helden nacheinander erstelle (in dem Fall nen Hexenzirkel)

> dann auf die Übersich gehe und speichern beim ersten drücke, kommt "Held gespeichert", das Feld bleibt beim ersten Char aber auswählbar

> edit: nein, es wird ausgegraut, wenn man aber den nächsten anklickt, wird es beim ersten (und mwn nur bei dem) wieder aktiviert

> und lässt sich unendlich oft anklicken

&mdash; **Atagon** on Discord

**Comment by pickbreaker** [comment]
Kann ich bestätigen. Der Fehler tritt bei mir auch bei mehreren veränderten Helden auf.

**Comment by elyukai** [comment]
@pickbreaker Kannst du ein Muster erkennen? Also unter welchen Umständen bzw. was ungespeichert sein muss, damit er die History nicht entsprechend setzt?

**Comment by elyukai** [comment]
I and others can't reproduce, so I'm going to close this. Please reopen *with concrete reproduction steps* if this still applies.
