### ISSUE TITLE
Zaubertricks

### ISSUE THREAD

**Issue by LLmichi1** [elyukai/optolith-client#247]
Die Zaubertricks haben zwar die Richtige Traditionsbeschreibung in der l10n, aber z.T. eine falsche oder unvollständige Spalte "traditions" in der univ

*Alte Fehlerbeschreibung:*
Kann mit Elfe u.a. Aura d. Eitelkeit und essenz der Niederhöllen (Tricks) auswählen. vmtl ein Fehler bei den AMIII-Tricks
M.S.: Der Trick "Blütenduft" aus AMA1 funktioniert auch nicht.

**Comment by Jordok** [comment]
Neue Cantriptabelle ist im Insiderordner (da ich TDE5 nicht editieren kann), korrigierte Einträge sind markiert.
