### ISSUE TITLE
[1.2.0-Alpha.6] Rasse: Zwerg, stronglyRecommendedDisadvantages wird doppelt angezeigt

### ISSUE THREAD

**Issue by Jordok** [elyukai/optolith-client#250]
**Describe the bug**
> Im Infofenster der Zwerge bei der Rassenauswahl wird der Punkt "Dringend Empfohlene Nachteile: Unfähig (Schwimmen)" doppelt aufgeführt.

**Expected behavior**
> Sollte nur einma angezeigt werden..

**Environment**
> Windows 10, 1.2.0-Alpha.6

**Comment by elyukai** [comment]
Valid for elves, too.
