### ISSUE TITLE
Tabellenfehler - Graumagier (Stoerrebrandt-Kolleg zu Riva) - Variante: Berater-Zweig

### ISSUE THREAD

**Issue by Onyxmoon** [elyukai/optolith-client#268]
**Describe the bug**
Gardianum ist fehlerhaft angegeben (mit -2) und wird deswegen nicht hinzugefügt.

**To Reproduce**
Beraterzweig wählen.

**Expected behavior**
Gardianum wird mit korrekten Werten hinzugefügt

**Screenshots**
![image](https://user-images.githubusercontent.com/8421390/69494520-114ba780-0ebd-11ea-920c-a7c9f7d1c88f.png)

**Environment**
 - OS: Windows 10
- Version: 1.2.0-alpha.9

**Comment by elyukai** [comment]
Habe Ulisses dazu eben angefragt

**Comment by elyukai** [comment]
*Impersona* sollte nur auf 4 sein, nicht auf 6. Laut Alex sind die Werte der Basisprofession bei einem Fehler grundlegend denen des Wahlzauberpakets vorzuziehen.
