### ISSUE TITLE
Advantage Large Spell Selection does not increase amount of possible spells

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#271]
> Wenn ich bei Eigene Profession einen Intuitiven Zauberer auswähle, und als Vorteil "Große Zauberauswahl I" oder "... II" aus wähle, kann ich trotzdem immer nur drei Zauber auswählen, obwohl es vier bzw. fünf sein sollten.

— From Discord

**Comment by Problembeloeser** [comment]
Problem persists with current Insider 1.3.0 alpha 0
[Pokku von Garnuks und Kisas Stamm.json.txt](https://github.com/elyukai/optolith-client/files/3964796/Pokku.von.Garnuks.und.Kisas.Stamm.json.txt)
