### ISSUE TITLE
Show weight as a new column in equipment list

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#305]
> Schön wäre auch, wenn in der Rubrik "Besitz" nicht nur "Name" und "Gruppe" als Spalte in der Tabelle kommen, sondern auch noch "Gewicht"

&mdash; **Knigge** on Discord

**Comment by Rahjenaos** [comment]
How should this look like?
Maybe like this?
![image](https://user-images.githubusercontent.com/4533505/84592935-6e06b380-ae49-11ea-8b27-0bc5e7254d29.png)

Items without (defined) weigth would show "-"
