### ISSUE TITLE
Keine Talentwertverringerung Fährtensuche mehr möglich bei Jäger (Kopfgeldjäger)

### ISSUE THREAD

**Issue by SimSch471** [elyukai/optolith-client#357]
Bei der Profession Jäger (Kopfgeldjäger) kann das Fährtensuchen nur gesteigert werden.
Der "-" Knopf ist dauerhaft ausgegraut

Ich habe 2 Screenshots und 2 Json Charakter angefügt.
 [Charakter Jsons.zip](https://github.com/elyukai/optolith-client/files/4024004/Charakter.Jsons.zip)

Bei dem Charakter ohne (2) kann Fährtensuchen noch 1x gesteigert werden (aber trotzdem schon nichts mehr abgezogen werden)
Bei dem Charakter mit (2) ist das Talent maximert.

Win 10

Optolith 1.2.0 (05.01.2020 heruntergeladen)

![9](https://user-images.githubusercontent.com/59540993/71785753-afc24100-3003-11ea-898d-b103120b7fd0.png)
![10](https://user-images.githubusercontent.com/59540993/71785754-afc24100-3003-11ea-9e3c-47fded334de4.png)

**Comment by elyukai** [comment]
Vielleicht ist das ein Bug in der Voraussetzung der Talentspezialisierung... Danke fürs Melden und die Charaktere, das macht das Suchen nach dem Fehler viel einfacher!! 🥰

**Comment by elyukai** [comment]
*Notiz für mich:* Das Problem ist, dass beim Hinzufügen der Dependencies beim Laden des Helden immer mit allen vorhandenen `ActiveObject`s gerechnet wird. Sie sollten also erst später eingefügt werden und bei der Gelegenheit sollten dann die Dependencies eingefügt werden.
