### ISSUE TITLE
Update to 1.2.0 cannot read existing data from 1.0.2

### ISSUE THREAD

**Issue by VolkerKamin** [elyukai/optolith-client#358]
**Describe the bug**
Installation von 1.0.2 nach 1.2.0

Programmstart meldet:
```
In object at key "meleeItemTemplatesCombatTechniqueFilter":
Expected: MeleeCombatTechniqueId, Received: "CT_8"
```

Anschließend hängt das Programm im Schritt `Lade und überprüfe Tabellen un Nutzerdaten`.

**To Reproduce**
1. 1.0.2 bereits nutzen
1. Installer von https://www.ulisses-ebooks.de/ herunterladen
1. Installer ausführen

Alternativ:
1. 1.0.2 bereits nutzen
1. Installer 1.1.2 ausführen (hatte ich noch im Download-Ordner, aber nie installiert)
1. Installer 1.2.0 ausführen

**Expected behavior**
normales Programmverhalten

**Screenshots**
n/a

**Environment**
Windows 10

**Additional context**
Der Desktop-Link zum Programm startet das neue Programm mit obigem Bug. Ein alter (manuell angelegter) Link im Startmenu startet Version 1.0.2, die weiterhin funktioniert.

Nach der ersten Installation von 1.2.0 habe ich 1.1.2 installiert (hatte ich noch ungenutzt rumliegen). 1.1.2 startet Problemlos und bietet Autoupdate an. Dieses führt zum Gleichen Problem wie der ulisses-ebooks-Installer. 1.1.2 benötigt bei jedem Programmstart einige Zeit für `Lade und überprüfe Tabellen un Nutzerdaten` und bietet anschließend das Update an. Wenn man dieses nicht annimmt, kann man 1.1.2 normal nutzen.

Unabhängig davon ob 1.1.2 oder 1.2.0 installiert ist, bleibt 1.0.2 weiterhin über den alten Link startbar.

Ich habe 23 Helden in verschiedensten Graden der Vollständigkeit (Teils nur Vorlagen für noch nicht unterstützte Professionen). Mal mit und mal ohne Portrait. Mehrere Helden existieren als Kopien in verschiedenen Steigerungsgraden.

**Comment by elyukai** [comment]
Prinzipiell kannst du das Problem beheben, indem du unter `AppData/Roaming/Optolith` die `config.json` löschst. Da sind auch keine wichtigen Daten drin, brauchst also kein Backup machen. Wenn du die 1.2.0 dann startest, sollte sie normal funktionieren.

Die 1.0.2 ist deshalb noch da, weil sie anders heißt als die aktuellen Versionen. Leider wird bei einer Umbenennung auch bei einem automatischen Update die alte Version dann nicht gelöscht. Du kannst (und solltest wahrscheinlich auch) sie manuell deinstallieren. Die 1.2.0 sollte davon dann nicht betroffen sein.

**Comment by elyukai** [comment]
Und bevor es zu spät ist als ohnehin schon: Danke für den ausführlichen Report!! 🥰
