### ISSUE TITLE
AMA1, AMA2, AMA3: Missing cultures 

### ISSUE THREAD

**Issue by Fletcher0306** [elyukai/optolith-client#360]
The following cultures are in Optolith Wiki but not selectable when creating new Charakters:

AMA1: Zahori
AMA2: Kobold worldler (Kobold Weltler), Plain elfs (Steppenelfen)
AMA3: Ferkinas, Gjalsker, Trollzacker
AMA3-Extra: Wild Dwarfs

**Comment by elyukai** [comment]
Did you make sure you switched the common cultures filter to *All Cultures*?

**Comment by Fletcher0306** [comment]
Hi, you are correct, i didn't switched to "all Cultures". Thereby the problem is solved
