### ISSUE TITLE
Unable to import a character right after exporting it

### ISSUE THREAD

**Issue by floriankramer** [elyukai/optolith-client#370]
**Describe the bug**
After creating a character and before finishing it I exported the character and was afterwards unable to import it again.

**To Reproduce**
I'm uncertain how to reproduce this (it doesn't fail in general, just for this character). This is the character's json (I changed the file extension for github):
[Astrid_Moonfall.txt](https://github.com/elyukai/optolith-client/files/4167763/Astrid_Moonfall.txt)

**Expected behavior**
The import of the json should work.

**Environment**
 - OS: Windows 10
 - Version 1.2.0

**Comment by elyukai** [comment]
Thanks for reporting! :) I'm gonna look into that.

**Comment by floriankramer** [comment]
I talked to the friend who originally created the character again. He recreated the character, and after comparing the export of the recreation and the original it appears that he opened the json in an editor and saved it unchanged. The editor prepended the file with a byte order mark (`EF BB BF`) which causes the import to fail with `{}` as the errormessage.

**Comment by elyukai** [comment]
I added a function that strips the UTF-8 BOM.
