### ISSUE TITLE
Allow edit of "Vorteile / Nachteile" on completed characters

### ISSUE THREAD

**Issue by VolkerKamin** [elyukai/optolith-client#375]
**Is your feature request related to a problem? Please describe.**
Many adventures allow characters to receive "Vorteile / Nachteile" although character creation is complete. By this, characters might also be allowed to exceed the 80 point limit.

For example, in 7G (DSA4), there are multiple adventures that give characters free AE / LE. In DSA5, I would like characters to be able to buy the "Vorteile" "Hohe Astralkraft" or "Hohe Lebenskraft" respectively.

As another example, when players perform extreme acts of good at great personal cost, I allow them to buy "Glück" (which you cannot by on level 3 in optolith as it is). This was the case when they handed over all age-restoring elixirs to victims of the ritual that brought back Borbarad instead of drinking them themselves.

As another example, a character might change during the course of a campaign. My mage (Schwert und Stab zu Beilunk(sic)) worked a lot for the KGIA in "Jahr des Feuers", which collided quite a bit with the oath to be always truthful. Hence, over time I payed off the "Nachteil" with AP and removed it eventually with the approval of the GM.

**Describe the solution you'd like**
Enable editing of "Vorteile / Nachteile" (maybe with a hint that this requires GM approval).

**Describe alternatives you've considered**
Writing on the print-out: meh :/

**Additional context**
n/a

**Comment by elyukai** [comment]
AFAIK this should be already possible by checking „Enable editing after hero creation“ in the global settings.

**Comment by VolkerKamin** [comment]
Awesome. Works.

Suggestion for FAQ

# Wie kann ich später Vorteile kaufen / Nachteile wegkaufen
Hierzu musst Du unter Einstellungen (Zahnrad rechts oben) die Option "Editieren von Helden nach der Heldenerschaffung" auswählen.

**Comment by elyukai** [comment]
Die Sache ist ja, dass das eigentllich nur mit Meistergenehmigung geht. Der Modus ist daher in gewisser Weise der "GM Mode" und ich weiß daher nicht, ob es sinnvoll ist, das so prominent zu platzieren. Auf der anderen Seite muss man natürlich trotzdem irgendwie darauf aufmerksam gemacht werden... 🤔
