### ISSUE TITLE
Zaubertrick Hexenblick für alle Zauberer wählbar

### ISSUE THREAD

**Issue by RondraLion** [elyukai/optolith-client#377]
Hallo ist es gewollt das der Zaubertrick Hexenblick für alle Magieanwender wählbar ist, denn in der Anmerkung steht "Ausschließlich Hexen". https://ulisses-regelwiki.de/index.php/ZT_Hexenblick.html

**Comment by elyukai** [comment]
Sollte wahrscheinlich nicht so sein. Ich überprüfe das! Danke! :)

**Comment by Jordok** [comment]
Selbes Problem besteht bei dem Zaubertrick Elfenhaar (CANTRIP_50), bei dem die Tradition (Elf) Voraussetzung sein sollte, auch so in der Datenbank ist, aber nicht funktioniert. 
Weiters scheint es ein tiefer gehendes Problem zu sein, da testweise eingebaute activatablePrerequisites auch bei anderen Zaubertricks nicht funkionieren.
