### ISSUE TITLE
Regelwerk ist zweimal anklickbar

### ISSUE THREAD

**Issue by RondraLion** [elyukai/optolith-client#385]
Hallo bei der Heldenerstellung. Taucht zwischen "Luftschlösser und Zauberwesen" und "Rüstkammer der Siebenwindküste". Das Regelwerk noch einmal auf.

**Comment by elyukai** [comment]
Welche Version nutzt du?

**Comment by RondraLion** [comment]
Das letzte Update der Insider Version.

**Comment by elyukai** [comment]
Ah, okay, das erklärt einiges! 👌 Am besten immer mit dazu sagen, dass du ne Insider verwendest, dann kann ich den Bug sehr viel besser eingrenzen.
