### ISSUE TITLE
Zauberalchimist kann Zauber/Zaubertricks erlernen

### ISSUE THREAD

**Issue by k0ntr4** [elyukai/optolith-client#430]
Beim Zauberalchimist steht in AMA2 Seite 40:

> Zauberalchimisten können keine Zauber erlernen (auch keine Zaubertricks).

Bei der Erstellung eines Zauberalchimisten muss man aber einen Zaubertrick lernen.
Auch kann man später Zaubersprüche erlernen.

**Comment by elyukai** [comment]
Ist im Regelwiki richtig als

> - Zauberalchimisten können keine Zauber erlernen (außer Zaubertricks).

angegeben: https://ulisses-regelwiki.de/index.php/Tra_Zauberalchimisten.html

Text muss also noch in Optolith entsprechend angepasst werden.

**Comment by elyukai** [comment]
**Quelle:** https://www.orkenspalter.de/index.php?thread/24203-sammelstrang-antworten-der-redaktion-auf-regelfragen/&postID=795393#post795393
