### ISSUE TITLE
Eigenschaftspunktvergabe fehlerhaft - Graumagier (Kampfseminar zu Andergast) 

### ISSUE THREAD

**Issue by Zgurgar** [elyukai/optolith-client#439]
**Describe the bug**
Beim erstellen eines Kampfmagier des Kampfseminar zu Andergast wird bei der Vergabe der Eigenschaftspunkte AP für die Punkte abgezogen.

**To Reproduce**

1. neuen Held erstellen
2. Graumagier (Kampfseminar zu Andergast) als Profession wählen
3. Eigenschaftspunkte vergeben

**Expected behavior**
Die Vergabe der Startpunkte für Eigenschaften sollten keine AP kosten.

**Screenshots**
![1](https://user-images.githubusercontent.com/15651604/75713942-12198400-5ccb-11ea-96e9-951cb4eeb862.png)
![2](https://user-images.githubusercontent.com/15651604/75713951-147bde00-5ccb-11ea-963e-b27732a9bf8c.png)

**Environment (please complete the following information):**

- OS:  Windows 10
- Version: 1.3.0-alpha.9

**Comment by elyukai** [comment]
Der MU-Wert ist aber auch um einen höher. Die AP-Kosten stimmen also. Aber der MU-Wert sollte sich nicht automatisch erhöhen.

**Comment by Zgurgar** [comment]
Ja, aber das sollte doch bis 100 Punkte keine AP kosten.

**Comment by elyukai** [comment]
Nein, jeder Punkt über 8 kostet.

**Comment by elyukai** [comment]
Und dabei ist es auch egal, welche Boni/Mali man durch Spezies/Kultur/Profession bekommt. Es werden immer nur Maxima beeinflusst, aber nie die wirklichen Werte; man bekommt also nichts "geschenkt".

Hat das Programm denn den MU-Punkt eingetragen oder hast du das gemacht?
