### ISSUE TITLE
Minor bugs in 1.3.1

### ISSUE THREAD

**Issue by VolkerKamin** [elyukai/optolith-client#471]
**Describe the bug**
- [x] SF Kraftkontrolle now requires "Leiteigenschaft 13" instead of "Leiteigenschaft 15". Used to be correct. Accidental "Verschlimmbesserung?" Faulty automatic mapping from SF Kleine Kraftkontrolle?
- [x] Drittanbieterlizenzen: "Last Changes could not be loaded" (also error message should read "Latest changes could not be loaded.")
- [x] No change log entry for 1.3.1

**To Reproduce**
trivial: just check the "i" of the SF.

**Expected behavior**
correct requirement

**Screenshots**
n/a

**Environment (please complete the following information):**
Win10
1.3.1

**Additional context**
n/a

**Comment by elyukai** [comment]
Yeah, forgot the changelog. xD Already committed the missing log, so it will be complete in the next version &ndash; as long as I dont forget the next one! XD
