### ISSUE TITLE
Dropdownmenu unleserlich

### ISSUE THREAD

**Issue by RondraLion** [elyukai/optolith-client#483]
Die Eingabefelder bei der Dropdownmenüs werden überlagert, wenn man etwas darin schreibt. 

Der Fehler tritt bei der Aktuellen Insider Version auf.

**Comment by elyukai** [comment]
Ich weiß leider nicht genau, was du meinst. Wo genau tritt es auf? Dropdowns gibt es einige in Optolith! 😜

**Comment by elyukai** [comment]
![grafik](https://user-images.githubusercontent.com/11094577/76124495-16131200-5ffb-11ea-954d-49abc2916744.png)

Der Hinweistext wird *nur* angezeigt, wenn Text vorhanden ist.
