### ISSUE TITLE
Bindung des Bannschwerts keine Kosten

### ISSUE THREAD

**Issue by TheColi** [elyukai/optolith-client#490]
Description:
Die Bindung des Bannschwerts kostet keine AP (Getestet bei Erstellung eines Characters wie auch beim Steigern.

![Bug Report Bannschwert](https://user-images.githubusercontent.com/61909698/76144800-1acfd880-6084-11ea-9d5e-ee1d455792ce.jpg)

- OS: Windows 10
- Version: 1.3

**Comment by elyukai** [comment]
Danke für die Meldung! 🥰 Ich kümmere mich drum.
