### ISSUE TITLE
Zu Niedrige Kampftalente bei Erstellung

### ISSUE THREAD

**Issue by TheColi** [elyukai/optolith-client#498]
Wenn Laut Professionspaket Kampftalente einen KTW >10 haben werden sie auf 10 gesetzt

- OS: Windows 10
- Version: 1.3

**Comment by elyukai** [comment]
Das ist in diesem Fall aber kein Bug, denn der Erfahrungsgrad erlaubt in diesem Fall nicht mehr, insofern wäre ein höherer KtW ein Verstoß gegen diese Regel. In Optolith steht das leider nicht als Anmerkung, in den Büchern allerdings schon.
