### ISSUE TITLE
Steppenelf aus Aventurische Magie 2 fehlt

### ISSUE THREAD

**Issue by blackecos** [elyukai/optolith-client#502]
Grüße,

keine hohe priorität aber die Steppenelfen "(Sub Spezies)" aus Aventurische Magie II fehlt. (Seite 227/ 228)

https://ulisses-regelwiki.de/index.php/Kult_Steppenelfen.html

**Comment by elyukai** [comment]
Ist in AMA2 wirklich eine Subspezies eingetragen? Ich habe da nur die Kultur gefunden. Und die Kultur kannst du ja freischalten, indem du anstatt "Übliche Kulturen" "Alle Kulturen" aktivierst.

**Comment by blackecos** [comment]
> Ist in AMA2 wirklich eine Subspezies eingetragen? Ich habe da nur die Kultur gefunden. Und die Kultur kannst du ja freischalten, indem du anstatt "Übliche Kulturen" "Alle Kulturen" aktivierst.

Ach da kann man sie finden okay. Habe die Frage so ähnlich im Discord gestellt, zu dem Zeitpunkt noch: "Ist eine Kultur" und dort wurde mir gesagt das es eine Sub Spezies ist und ich hier einen Thread öffnen soll.
Dann hat es sich erledigt.

Grüße
