### ISSUE TITLE
Falsche und fehlende Befehle in CONTRIBUTING.md

### ISSUE THREAD

**Issue by JackWolfskind** [elyukai/optolith-client#503]
Hallo,

nur eine Kleinigkeit, in der CONTRIBUTING.md steht das man `npm run compile` und `npm run watch` ausführen kann.

Die Befehle wurden aber im Commit a477927b622ffcd8f51fcc87e272c4c5bd688802 auf tsc:watch und tsc:build geändert.

Grüße

**Comment by elyukai** [comment]
Ähm, ja, da war ja noch was 😅🙈

**Comment by elyukai** [comment]
Dann kann ich auch noch die Befehle für Reason und so hinzufügen.
