### ISSUE TITLE
Unfamiliar spells count towards unfamiliar limit by EL

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#518]
> er scheint den gewählten zuaber gegen das fremdzauber limit zu rechnen
> ich habe einmal axxeleratus gewählt, dann zeigt er mir danach pandaemonium nicht mehr an
> umgekehrt das selbe bloß gespiegelt

&mdash; **Tenshouko** on [Discord](https://discord.com/channels/366655545236783114/449257886376394752/689478437282381924)

**Comment by JoveToo** [comment]
The transferred spell for the Tradition guild mage still counts against the limit of unfamiliar spells from the EL – which should not happen

**Comment by elyukai** [comment]
Seems to be fixed. Please reopen if my observation was wrong.
