### ISSUE TITLE
Tradition Hexen - Falsche Kosten

### ISSUE THREAD

**Issue by blackecos** [elyukai/optolith-client#530]
Grüße,

ein kleiner Fehler:
Tradition: Hexen kostet in Optolith 125 AP
Laut Regelwerk kostet es aber 135 AP.

**Comment by elyukai** [comment]
Moin!

Kann es sein, dass du vielleicht die Nachteile Keine Flugsalbe oder Kein Vertrauter gewählt hast? Die verringern die Kosten der SF um jeweils 10. Ich habe eben auch nachgeschaut, die SF ist mit 135 AP hinterlegt.

**Comment by blackecos** [comment]
Das habe ich vergessen, tut mir leid.
(Der automatische Heldenbogen beachtet das übrigens nicht. ^^)

**Comment by elyukai** [comment]
Alles gut!! 😉 Im Zweifelsfall immer Bescheid geben, man kann einfach nicht alle Regeln im Kopf haben, that does not work, aber es sind halt auch häufig einfach Fehler, und das "schlimmste", was dann passieren kann, ist, dass es kein Fehler ist. Aber lieber so herum als dass es ein Fehler wäre, den aber nicht meldet. Insofern trotzdem danke!! 🙏🏻🥰
