### ISSUE TITLE
Missing Magierkugelzauber 'Konservierungsgefäß'

### ISSUE THREAD

**Issue by Ramesch** [elyukai/optolith-client#532]
**Describe the bug**
As I could not find the English translation, I use German names (sorry for that):

When you have 'special ability' 'Bindung der Magierkugel' you can put some special abilities on it (AMAII p. 15). I can not find 'Konservierungsgefäß' (AMAII p. 17), but I don't know if it only belongs to the abilities of my hero or if this special ability is missing.

**To Reproduce**

1. Open a mage hero
2. Go to 'abilities' -> 'special abilities'
3. Try to add 'Konservierungsgefäß'

**Expected behavior**
Possibility to take 'Konservierungsgefäß'

**Environment:**
- OS: Kubuntu 18.10
- German
- Version: 1.3.1

**Additional context**
Special ability 'Bindung der Magierkugel' only shows up when 'German' language is active, but this may belong to missing English rule book?

**Comment by elyukai** [comment]
Did you active the SA "Aufbewahrung"? Because that's a prerequisite for "Konservierungsgefäß".

**Comment by Ramesch** [comment]
Oh, darn, I missed that. Then this all works as it should and I close this bug report. Sorry!

**Comment by elyukai** [comment]
No worries!!! It's way better to report an error which turns out *not* to be one instead of not reporting sth. that *turns* out to be one! So I still want to thank you for reporting!! 🙏🏻🥰
