### ISSUE TITLE
Item ‚mage orb‘ is missing (no rule book)

### ISSUE THREAD

**Issue by ghost** [elyukai/optolith-client#533]
**Is your feature request related to a problem? Please describe.**
There are many orb spells (‚Kugelzauber‘) for a mage but there is no item mage orb (‚Magierkugel‘) in existing rule books and Optolith client.

Since the mage orb is mentioned in AMA I, AMA II and Herbarium, but none of these books mentioned the properties like price, weight or size, I add the mage orb according to the Ulisses Regelwiki (see https://ulisses-regelwiki.de/index.php/magierkugel-7527.html ).

**Describe the solution you'd like**
A standard item for mage orb in Optolith client. 

**Describe alternatives you've considered**
As the properties are not mentioned in any rule book and Optolith currently only implements items which belongs to this content you have to create a custom item for each hero who wants to use it.

**Additional context**
Maybe this could also be added as a request for Ulisses?

**Comment by elyukai** [comment]
I'm gonna send it to them as a request. I can only include what is "official", since everything else would always kind of a personal preference. Thanks for mentioning the issue!
