### ISSUE TITLE
Verbessertes Ausweichen wird nicht dem wert aufgerrechnet

### ISSUE THREAD

**Issue by DeadInside147** [elyukai/optolith-client#542]
**Describe the bug**
Die Verbessertes Ausweichen Sonderfertigkeit wird nicht auf den Ausweichen Wert im Characterbogen aufgerechnet.

**Expected behavior**
Wenn Verbessertes Ausweichen genutzt wird sollte der Wert im Characterbogen dementsprechend Steigen.

**Environment (please complete the following information):**

- OS: Windows 10
- Version: [1.3.0]

**Comment by elyukai** [comment]
Das ist so vorgesehen, da Optolith (noch) nicht weiß, ob du eine Rüstung trägst und wenn ja, welche. Das kommt erst später mit #59. Ein vergleichbarer Issue ist auch #320 – nur auf Englisch.
