### ISSUE TITLE
Select options of Traditions Arcane Bard and Arcane Dancer don't require their respective culture

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#565]
> Bei den zauberbarden kann ich mit Kultur thorwaller auch die anderen Varianten auswählen und deren lieder nutzen

&mdash; **Xardai** on Discord

**Comment by JoveToo** [comment]
As far as I could tell, only the Ceoladir was missing its culture dependency (mittelreicher).

**Comment by elyukai** [comment]
Basically what is meant is that the *Traditions* (Special Abilities) do not have culture prerequisites. So they need to be added to their select option entries

**Comment by Jordok** [comment]
as of version 1.4.0_Alpha.10 this works correctly
