### ISSUE TITLE
Typo in EL "Brilliant"

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#567]
> "Brillant" wird sowohl bei der Erfahrungsgrad-Auswahl zu Beginn einer Heldenerstellung als auch auf dem fertigen Heldenbogen falsch "brilliant" geschrieben

— **Mallkalai** on Discord

**Comment by Rahjenaos** [comment]
Dieser Typo kommt noch öfter vor:
* Brillantzwerge
* Brillant
* Brillanter Telekinetiker
