### ISSUE TITLE
Disable auto-update warnings when not using AppImage on Linux

### ISSUE THREAD

**Issue by JoveToo** [elyukai/optolith-client#573]
**Is your feature request related to a problem? Please describe.**
When not using an AppImage, the auto updater cannot actually download an update on Linux.

**Describe the solution you'd like**
The auto-updater would pop up a message saying "There is an update available" (perhaps with a version number and download link) or would be silent if no update is available.

**Comment by elyukai** [comment]
I added a function that tries to handle this. If anyone uses Linux, please verify if this has been fixed or not. Thanks!
