### ISSUE TITLE
Disable updater alerts and Check for Updates button on macOS

### ISSUE THREAD

**Issue by thebodo** [elyukai/optolith-client#589]
**Describe the bug**
Optolith is not able to update itself.

**To Reproduce**

1. Go to 'Settings' (click on cogwheel in the upper right corner)
2. Click on 'Nach Updates Suchen'
3. Click on 'Aktualisieren'
4. The Dialog flickers
5. Click on 'Aktualisieren'
6. The dialog flickers OR an empty error message is shown (this might also take a third click on Aktualisieren)

**Expected behavior**
Update would start or at least a reasonable error message should be shown.

**Screenshots**
<img width="1484" alt="Bildschirmfoto 2020-05-18 um 23 03 47" src="https://user-images.githubusercontent.com/26524604/82259758-5fb59c80-995c-11ea-93f4-a55149c4827f.png">
<img width="1483" alt="Bildschirmfoto 2020-05-18 um 23 04 05" src="https://user-images.githubusercontent.com/26524604/82259858-8378e280-995c-11ea-8b73-dec11890efa1.png">

**Environment (please complete the following information):**

- OS: Mac OS 10.15.4
- Version: V1.2.0

**Additional context**

**Comment by elyukai** [comment]
This is a current limitation on macOS, since I can't code-sign and notarize the app right now. I have to disable those messages and the button, though, so that it suggests to do sth it actually cannot do.

I'm gonna change the topic that way.

Thanks! :)
