### ISSUE TITLE
Tradition Arcane Dancer, Sharisad: Cannot add dances

### ISSUE THREAD

**Issue by RondraLion** [elyukai/optolith-client#594]
Ich wollte mir gerade eine Sharizad bauen. und irgendwie kann ich keine weiteren Tänze auswählen
Alle die im Professionspakte drin sind, sind vorhanden. Aber ich finde über die suche keine weiteren.
Das habe ich jetzt bei der Insider Version gemerket, ob das bei der Public Version auch ist, weiß ich nicht.

![grafik](https://user-images.githubusercontent.com/11094577/82556354-dbd0ff80-9b69-11ea-92e7-71ac5c41ebdc.png)

**Comment by Rahjenaos** [comment]
![image](https://user-images.githubusercontent.com/4533505/82739839-7df80f80-9d43-11ea-9660-1cd8be86416e.png)
ich habe es gerade mit einer schnell neu generierten Tänzerin versucht - habe allerdings "eigene Profession" gewählt und dann einfach nur  den Vorteil Zauberer sowie die Sonderfertigkeit Tradition Zauberzänzer hinzugefügt. 
Gibt's evtl noch weitere infos von @RondraLion ?

**Comment by Gamarc** [comment]
Das Problem beschränkt sich nicht nur auf Sharisads, auch bei den Professionen Majuna und Rahkisa lassen sich keine Zaubertänze hinzufügen. Bei Hazaqis dagegen lassen sich nur Tänze der Musiktradition Sharisad hinzufügen.
In allen Fällen starten die Helden zwar mit den Tänzen aus dem Professionspaket, diese lassen sich aber nicht wieder hinzufügen falls man sie entfernt.
Fügt man die Sonderfertigkeit Tradition (Zaubertänzer) von Hand hinzu stehen die korrekten Tänze zur Auswahl, daher funktioniert auch bei "eigenen Profession" alles.

**Comment by elyukai** [comment]
Ah, ja, dann glaube ich weiß ich, was das Problem ist. Danke für die Ergänzung!
