### ISSUE TITLE
Translations missing for new feature of adding / subtracting money

### ISSUE THREAD

**Issue by Rahjenaos** [elyukai/optolith-client#609]
I could only provide DE & EN in https://github.com/elyukai/optolith-data/commit/b09f234268fd1950f0caae144272e64ac86b8945

Missing languages:

- [x] French
- [x] Dutch
- [x] Italian

**Comment by JoveToo** [comment]
Added Dutch translation https://github.com/elyukai/optolith-data/pull/28
