### ISSUE TITLE
Aspect Knowledge [Healing] cannot be chosen for Blessed Ones of Peraine with 3 chants on 10+

### ISSUE THREAD

**Issue by Infinitum31415** [elyukai/optolith-client#612]
**Describe the bug**
Selbst wenn alle Bedingungen für die Aspektkenntnis [Heilung] erfüllt sind (Intuition 15, 3 Heilungs-Liturgien 10+, 3 Heilungs-Zeremonien 10+) ist die Sonderfertigkeit 'Aspektkenntnis' nicht auswählbar.
Wenn 3 (bzw. 6) Liturgien/Zeremonien für Landwirtschaft gewählt wurden, ist die Aspektkenntnis hierfür auswählbar.

**To Reproduce**
Erstelle einen Peraine Geweihten, der alle Voraussetzungen für Aspektkenntnis [Heilung] erfüllt und versuche die Sonderfertigkeit auszuwählen.

**Expected behavior**
Die Sonderfertigkeit Aspektkenntnis [Heilung] sollte verfügbar sein.

**Screenshots**
![image](https://user-images.githubusercontent.com/3732095/83966967-ec99a900-a8bd-11ea-8506-a071a10982c6.png)
![image](https://user-images.githubusercontent.com/3732095/83966973-f7ecd480-a8bd-11ea-98aa-b3d445959895.png)
![image](https://user-images.githubusercontent.com/3732095/83966984-0509c380-a8be-11ea-8150-20a287641499.png)

[Jasper_Lafanti_bug.zip](https://github.com/elyukai/optolith-client/files/4741841/Jasper_Lafanti_bug.zip)

**Environment (please complete the following information):**

- OS: Windows 10
- Version: 1.3.2

**Additional context**

**Comment by elyukai** [comment]
Danke für deinen ausführlichen Bugreport!!! 🤗 Aber kann es sein, dass #591 den gleichen Fehler beschreibt? 🙈🙈🙈😭

**Comment by Infinitum31415** [comment]
> Danke für deinen ausführlichen Bugreport!!! 🤗 Aber kann es sein, dass #591 den gleichen Fehler beschreibt? 🙈🙈🙈😭

Sehr wahrscheinlich ;-) Muss zugeben, dass ich den nicht gefunden habe, da ich DSA nur auf deutsch spiele und mit den englischen Bezeichnungen/Übersetzungen nicht vertraut bin.

**Comment by elyukai** [comment]
Alles gut!! 🙈 Ich bin gerade am überlegen wie ich die zusammenführe. Englisch ist idR einfach besser, weil es dann auch die leute, die Optolith auf Englisch, Niederländisch, Französisch oder bald Italienisch nutzen, verstehen können. Aber dein Issue ist einfach viel detaillierter als das, was ich da hingeschmissen habe! 😅🙈

**Comment by Infinitum31415** [comment]
I could translate it. I just wrote it in german because I'm not familiar with the english translation of DSA^^

**Comment by elyukai** [comment]
Well, I think it’s all good, it would be great if you could translate the title, though, that should be enough! 🤗 I’m gonna close the other issue then.

**Comment by Infinitum31415** [comment]
>  Aber dein Issue ist einfach viel detaillierter als das, was ich da hingeschmissen habe!

Bin ja selbst software entwickler und versuche daher immer, bug reports möglichst ausführlich zu schreiben ;-)

> [...] it would be great if you could translate the title, though, that should be enough!

Done.

**Comment by elyukai** [comment]
> Bin ja selbst software entwickler und versuche daher immer, bug reports möglichst ausführlich zu schreiben ;-)

Oh man, ich fühle mich schlecht. 😅🙈 Ich hab leider nicht immer so viel Zeit und verweise daher meist nur genau auf das, was die Leute geschrieben haben, bzw. was die und ich in ner Diskussion dazu noch gesagt haben, damit ich die Zeit, die ich habe, dann auch wirklich für Optolith nutzen kann... Manchmal wäre es toll, wenn ich das beruflich machen könnte, dann würde ich damit auch noch etwas anders umgehen 😅🙈

> Done.
Thank youuuu!! 🥰🥰🤗

**Comment by Infinitum31415** [comment]
> Oh man, ich fühle mich schlecht

alles gut ;-) wollte dich nicht kritisieren^^ fühle mich ja eher selbst schlecht, dass ich nicht die Zeit und Muße habe, mich an so 'nem open source Projekt zu beteiligen :)

**Comment by elyukai** [comment]
> alles gut ;-) wollte dich nicht kritisieren^^ fühle mich ja eher selbst schlecht, dass ich nicht die Zeit und Muße habe, mich an so 'nem open source Projekt zu beteiligen :)

Alles gut, hab’s auch nicht so aufgefasst. Ich fühle mich nur schlecht, weil ich weiß, dass ich es nur sehr stümperhaft mache bzw. machen muss – und dann sehe ich solche ausführlichen Reports... 😭😅🙈

Und naja: Bug Reports sind genauso wichtig wie Coden oder auch anderes Feedback – finde ich jedenfalls. Insofern... 🤗

**Comment by Infinitum31415** [comment]
ich kenne halt unzureichende bugreports von kunden (sowas wie *X ist kaputt*). damit kann man halt nicht viel anfangen^^ 

ein ausführlicher report ist halt wichtig, für den, der es hinterher analysiert, sonst hast du ja oft keine chance^^

**Comment by elyukai** [comment]
Stimmt schon. Ich versuche dann halt immer alles was zur Eingrenzung des Problems notwendig war, mit einzubinden. Das reicht auch meistens. Aber ein übersichtlicher Report ist dann halt nochmal etwas schöner, allein schon, weil er so schön aufgeräumt ist.

„X ist kaputt“ nehme ich nur auf, wenn klar ist, was genau kaputt ist... 😅🙈 Und dann braucht man häufig tatsächlich auch gar nicht mehr Input.

**Comment by ZeSandman** [comment]
Even if it's not written in english, CTRL-T is your friend in Chrome :)

At lest, that's how I browse those bug reports :p

And Troubleshooting has it's own "Minding" that one needs to be in or know about to do efficiently.
Source: Telecom network support for 20+ years, mostly by phone, with clients complaining "it's not working!!!!" :p

**Comment by elyukai** [comment]
> At lest, that's how I browse those bug reports :p
I'm sorry!! 😭🙈 

> And Troubleshooting has it's own "Minding" that one needs to be in or know about to do efficiently.
That's true!

**Comment by ZeSandman** [comment]
You don't have to be sorry (stop that!, someone will think you're Canadian! and I don't like competition :p)
