### ISSUE TITLE
Combat Techniques page duplicated in character sheet (german language setting only)

### ISSUE THREAD

**Issue by Infinitum31415** [elyukai/optolith-client#616]
**Describe the bug**
Wenn *deutsch* als Sprache eingestellt ist, wird die Seite `Kampftechniken` im Heldenbogen 2x dargestellt (mit minimalem Unterschied im `Rüstungen` Feld (siehe attachment).
Mindestens mit *englisch* als eingesteller Sprache, tritt dieser Fehler **nicht** auf.

**To Reproduce**
1. Stelle *deutsch* als Sprache ein
2. Starte Optolith neu
3. Erstelle einen Charakter und beende Charakter-Erschaffung
4. Öffne `Heldenbogen` tab.

**Expected behavior**
Die `Kampftechniken` Seite sollte nur 1x im Heldenbogen enthalten sein.

**Screenshots**
![image](https://user-images.githubusercontent.com/3732095/84402875-53dc9380-ac05-11ea-8997-2477759b57c7.png)
`Rüstungen-Seite 1`:
![image](https://user-images.githubusercontent.com/3732095/84403063-8f775d80-ac05-11ea-9f3a-6705cc9a2c3c.png)
`Rüstungen-Seite 2`:
![image](https://user-images.githubusercontent.com/3732095/84403103-9a31f280-ac05-11ea-998d-28bba9bf251f.png)

**Environment (please complete the following information):**

- OS: Windows 10
- Version: 1.3.2

**Additional context**
[test.zip](https://github.com/elyukai/optolith-client/files/4765633/test.zip)
[test_character.pdf](https://github.com/elyukai/optolith-client/files/4765648/test_character.pdf)

**Comment by elyukai** [comment]
Das ist beabsichtigt, da man sich so aussuchen kann, welchen Bogen man drucken möchte. Es verhält ich in dem Punkt (noch) wie der Selbstrechnende Heldenbogen, der das auf die gleiche Weise macht. Idealerweise sollte der Bogen ausgeblendet werden, wenn keine Zonenrüstung zum Einsatz kommt; umgekehrt sollte das Blatt mit normaler Rüstung ausgeblendet werden, wenn man Zonenrüstung, aber keine normale Rüstung hat. Dieses Feature wird von #407 getrackt.

**Was** allerdings ein Bug ist, ist, dass er für englische **gar** nicht angezeigt wird, denn die gibt es ja mittlerweile schon auf Englisch.

**Comment by Rahjenaos** [comment]
Der englische Bogen wird angezeigt wenn als Fallback Language Deutsch eingestellt ist.
Immerhin dann sogar mit den korrekten englischen Begriffen

**Comment by Rahjenaos** [comment]
Visibility of the Hit Zone ArmorTab is also linked to "Aventurische Rüstkammer 1". You cannot select that rule book unless you set German as fallback language but you will have a perfectly translated tab afterwards.
is that by intention?

**Comment by elyukai** [comment]
No. Well, kind of. The English Armory has been added recently but I forgot to update that tab for that. It's not an elegant solution in general, though. It should be in the info of the books if there should be a Hit Zone Armor tab. But the current solution should be ok for now.

**Comment by elyukai** [comment]
The combat sheet with hit zone armor is shown on demand and #1328 has been fixed, so the issue in the code discussed here does not apply anymore.
