### ISSUE TITLE
Missing weapons from MOA1

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#617]
All weapons on MOA1 p. 233 (German ref) are missing in the database.

**Comment by Jordok** [comment]
Erledigt.
Dokumentation potentieller Probleme:
A) scharlatanische Zauberkugel ist nun 2 mal vorhanden (1x 2H-Hiebwaffe, 1x Wurfwaffe)
B) Gewicht der Zauberstecken und Magierstäbe (bei allen Längen ident)
C) Improvisierte Waffenwerte der Musikinstrumente
