### ISSUE TITLE
Elfenfreund needs errata

### ISSUE THREAD

**Issue by JoveToo** [elyukai/optolith-client#621]
**Describe the bug**
The Elfenfreund special ability says it doesn't give an additional difficulty of 1 as fremdzauber. Fremdzauber give normally 2 additional difficulty. 
http://www.ulisses-gamereference.com/index.php/Elfenfreund.html has an errata. It should be included in Optolith.

**Comment by elyukai** [comment]
To quote the errata section in the RegelWiki: 

> Aventurische Magie - 4. Auflage: Die Fremdzauber-Erschwernisse von 2 werden bei Elfenzaubern nicht angewendet. [Anmerkung: Antwort der Redaktion (17.02.2019) besagte eine Reduzierung der Erschwernisse durch die Fremdtradition um 1. Dies ist ist mit der 4. Auflage erneut angepasst worden.]
