### ISSUE TITLE
italian translation for sheets.useparchment missing

### ISSUE THREAD

**Issue by Rahjenaos** [elyukai/optolith-client#625]
The last language missing for this feature is italian. It is only a single line:
sheets.useparchment: "Use Paper Texture"

It is used next to a checkbox on the left of the character sheet (here "Papiertextur verwenden"):
![image](https://user-images.githubusercontent.com/4533505/85032122-bee71680-b17f-11ea-8655-1c571663dc51.png)

**Comment by elyukai** [comment]
Seems to be fixed and I forgot to close this. 😬
