### ISSUE TITLE
Freeform text for "Personality Flaw" is visible not always greyed-out (unavaiable)

### ISSUE THREAD

**Issue by ZeSandman** [elyukai/optolith-client#627]
This has been talked about in the french BBE/ON Boards

I'm not sure if it's a bug, but it seems like one

The Personality Flaw disadvantage seems to have an empty field to add a custom flaw, but it can't be enabled, unlike Bad Habit/Obligations/Principles/Stigmata...

**Comment by elyukai** [comment]
It’s not for custom personality flaws but for additional information on _Unworldly_ or _Prejudice_. 

So it’s output would be _Personality Flaw (Prejudice: Novadi)_ or sth like that.

At least that’s how it’s supposed to work.

**Comment by ZeSandman** [comment]
Ok... so would it be possible to have a custom flaw field then? (maybe select "Custom" and we can add our own ?)

**Comment by elyukai** [comment]
Kind of. I’m not sure if I should implement it that way. I’m not that fan of having a „Custom“ option – it always looks out of place – and I’d also need to provide another option since personality flaws cost either 5 or 10 AP.

**Comment by ZeSandman** [comment]
Right... though it seems that a lot of people want personality flaws not in the "official lists"   A bit like Stigmatas, the list is pretty short and everyone taking it ends up being ablinos :(

you could have "custom 5pt" and "custom 10pt"

**Comment by elyukai** [comment]
I'm closing this in favor of a "proper" feature request: #708.
