### ISSUE TITLE
Custom advantages/disadvantages/special abilities – temporary solution

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#632]
**Is your feature request related to a problem? Please describe.**
The feature is already described in #28 and #215, but it’s implementation would be very time-consuming. This feature tries to provide a temporary solution for custom entries that is way easier to implement.

**Describe the solution you'd like**
There would be a new entry for advantages, disadvantages and special ability, that would be called „Own Advantage/Disadvantage/Special Ability“ (depending on the list) with an input field to define the actual name of the entry and the ability to customize the AP – even for special abilities.

**Describe alternatives you've considered**
Mentioned in the issues referenced above.
The downside of this approach obviously is that you can only define name and AP value. But that makes it so easy to implement, which is something that should be considered since a lot of people ask for custom entries.

**Comment by JoveToo** [comment]
Please allow for a description field in addition to name and AP.

It would probably be easier to store this with the character itself.

**Comment by elyukai** [comment]
The description field cannot be shown afterwards, so that wouldnt make much sense. The entry will not be able to show customized wiki entries in the sidebar based on the description field. An it cant be added to the name, since that would make it way too long.

**Comment by JoveToo** [comment]
:'(

**Comment by elyukai** [comment]
I'm thinking of how to Display them on the character sheet. There are several options I can think of based on the given values "name" and "AP value".

- Custom Special Ability (Plant Artist, 10 AP)
- Custom Special Ability (Plant Artist)
- *Plant Artist*
- Plant Artist (10 AP)

Personally, I like the last one most, since you'll see it's custom just because of the AP value – and you'll see the custom AP value, since it can't be fixed.

I would not display it without any note that it's a custom entry.

**Comment by JoveToo** [comment]
I agree with including a note it is a custom entry. I would opt for option 2 or 4.
I don't really need to know the AP on my character sheet but perhaps 2 is too long.

**Comment by elyukai** [comment]
If there are a lot of custom entries, you'll always have this "Custom Special Ability" filling half the space ... 😅😅🙈
