### ISSUE TITLE
Typo in effect of Metessa Galora-Stil

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#635]
> Regel: Setzt eine Heldin mit diesem Stil eine Finte ein, kann sie statt der Senkung der Verteidigung des Gegners, Rüstungsschutz durch extern getragene Rüstungen in der Höhe der Stufe der Finte ignorieren. Zudem erleidet sie durch gegnerischeFinten nur die Hälfte der Erschwernis.

&mdash; **Hagen** on Discord

**Comment by Jordok** [comment]
im aktuellen develop Repo bereits gefixed. (Stand 28.7.20)
