### ISSUE TITLE
Zeremonialgegenstände des Numinoru-Geweihte

### ISSUE THREAD

**Issue by Jordok** [elyukai/optolith-client#653]
Bei den Zeremonialgegenständen des Numinorugeweihte wird der Effekttext nicht angezeigt (Obwohl der Text im System ist).
Vermutlicher Fix: für den Effekttext "effect" statt "rules" verwenden.

**Comment by elyukai** [comment]
Ja, da müsste tatsächlich `effect` statt `rules` verwendet werden.
