### ISSUE TITLE
War Lance does not show on character sheet

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#662]
**Describe the bug**
> Weiss nicht ob das bekannt ist, aber: Ich habe gerade alles mögliche versucht um eine Kriegslanze im Heldenbogen unter Nahkampfwaffen angezeigt zu bekommen, aber sie wird nur im Besitz angezeigt, nicht unter Nahkampfwaffen. Hab auch versucht es als Ausrüstung zu setzen und dann improvisierte Waffe, aber auch das klappt nicht.

**To Reproduce**
—

**Expected behavior**
It should be shown on character sheet, even though it doesn't have a PA value.

**Screenshots**
—

**Environment (please complete the following information):**

- OS: Windows 10
- Version: 1.4.0-alpha.10

**Additional context**
—

**Comment by Jordok** [comment]
Trifft auch auf die Tunierlanze zu.
Im Detail scheint es daran zu liegen, das weder die Tunierlanze noch die Kriegslanze laut Regelwiki eine definierte Schadensschwelle besitzen. Die Ferdoker Kriegslanze besitzt allerdings eine, und sie wird als einzige korrekt angezeigt.
Wird bei einer der anderen Lanzen ein damageThreshold hinzugefügt, werden sie korrekt angezeigt.
