### ISSUE TITLE
Issue mit Zaubertänzen

### ISSUE THREAD

**Issue by Fressi105** [elyukai/optolith-client#668]
Hey, hoffe ich wiederhole keine andere Anregung. Für mich sind kurioserweise beim Erstellen eines/einer Hazaqi die Tänze der Sharisad wählbar und von denen der eigentlichen Ausrichtung fehlt jede Spur.

![Tänzer1](https://user-images.githubusercontent.com/69820074/90440476-94f69580-e0d7-11ea-821e-dbdba367dee7.png)

Wollte mir einen Hazaqi erstellen und die exlusiven Tänze wie Tanz des Feuers oder des Blutrauschs wählen, war aber erstaunt, dass ich sie nicht gefunden habe. 
Zuerst dacht ich, ich mache etwas falsch (was immernoch gut möglich wäre) und habe daraufhin die Tänze im Wikibereich nachgeschaut, da ich anfangs dachte sie wären schlicht noch nicht hinzugefügt. Dort fand ich sie unter den Zaubern gelistet, woraufhin ich unter den Bedingungen einer neuen Heldenerstellung versuchte sie erneut auszuwählen, aber wieder ohne Erfolg war. Wie schon angedeutet kann ich jedoch Tänze wie den Tanz der magischen Gemeinschaft hinzufügen, obwohl die von mir ausgwählte Musiktradition der Hazaqi dies unter Normalbedingungen (außer man spielt mit der Optionalregel des Erlernens von fremden Tänzen) nicht zulässt. Unten ein Auschnitt von der Übersichtsseite mit Spezies, Klutur, etc..

![Tänzer2](https://user-images.githubusercontent.com/69820074/90441379-24e90f00-e0d9-11ea-9e10-c7f61f7aa62f.png)
 
Inzwischen habe ich den Versuch mit verschiedensten Parametern getestet aber selbt wenn man die Sharisad anfänglich wählt scheint man manche Tänze nicht wählen zu können. Zusätzlich scheint es so, dass wenn man bereits in der Profession inkludierte Zaubertänze entfernt und wieder hinzufügen möchte, diese nichtmehr in der Liste auftauschen.

Ich besitze Win10 und führe Optolith in der neusten öffentlichen Version (1.3.2) aus.
Hoffe das hier ist keine Dopplung und vielen Dank für eure Arbeit!

**Comment by elyukai** [comment]
Hi! 👋🏻

Danke für deine ausführliche Bugbeschreibung!!! 😍

Gerade deswegen tut es mir aber sehr leid, dir sagen zu müssen, dass der Bug bereits gemeldet wurde und auch bereits als Issue existiert. 🙈🥺 Nämlich hier: #594 

Trotzdem: **Vielen Dank** für deine Meldung und auch und besonders, dass du dir die Zeit genommen hast, es hier auf GitHub zu machen!!! <3
