### ISSUE TITLE
TypeScript Errors because of missing properties in L10n

### ISSUE THREAD

**Issue by Midori-307** [elyukai/optolith-client#689]
**Describe the bug**
The TypeScript Compiler laments that the L10n type is missing some properties.

**To Reproduce**
run `npm run ts:build`

**Expected behavior**
No TypeScript Errors

**Screenshots**
Compiler outputs (provided by Incendor): https://pastebin.com/PBAiECku

**Comment by elyukai** [comment]
The basic TS definition comes from the `optolith-data` repositories. This issue occurs if you checkout different branches that make different assumptions about the possible keys, such as if you checkout `master` in one repo and `develop` in the other.

Which branches did you checkout?

**Comment by Midori-307** [comment]
As you suspected, the actual issue was that I checked out the `master` branch of the client and the `develop` branch of the data repositories. 
With the new submodules approach, this problem can be avoided altogether.
