### ISSUE TITLE
Hagelschlag und Sturmgebrüll is missing traditions

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#717]
**Describe the bug**
Hagelschlag und Sturmgebrüll doesn't react to a transfer into the own tradition (Geode).

**To Reproduce**
—

**Expected behavior**
It should not be marked as unfamiliar anymore.

**Screenshots**
—

**Environment (please complete the following information):**

- OS: Windows 10
- Version: 1.3.2

**Additional context**
https://www.orkenspalter.de/index.php?thread/23638-optolith-heldengenerator/&postID=1020408#post1020408

**Comment by Jordok** [comment]
Fehler (Vermutlich) Identifiziert.
Mit Hagelschlag und Sturmgebrüll läuft nichts falsch, aber der "Gildenloser Magier (Schüler des Vadif sal Karim)" erhält ebenso wie der Sturmherr Geode statt Hagel&Sturm nur Hagelschlag. Zumindest ist dies die einzige Erklärung die reproduzierbar ist und ansatzweise mit der Fehlerbeschreibung zusammenpasst.
