### ISSUE TITLE
Animal Companion Talents text field too short on PDF export

### ISSUE THREAD

**Issue by madmath74** [elyukai/optolith-client#733]
**Describe the bug**
When adding an animal companion to a character and filling the Talent text field with several Talents, the PDF export is not showing all of the entries. 
It seems like the text field in Optolith is bigger than the one in the PDF.

**To Reproduce**

1. Create Character completely, but do not press finish
2. Add animal Companion on Animal companion page and add talents according to DSA Regelbuch
3. Finish Character
4. Show PDF Character Sheet and export
5. Search for aninmal companions talents.

**Expected behavior**
Either the Talent text field in Optolith should be limited or the PDF Export should show all given / noted talents of the animal companion

**Screenshots**

**Environment (please complete the following information):**

- OS: [e.g. Windows 10] Windows 10 Pro, Version 2004, Build 19041.508
- Version: [e.g. 1.1.0, 1.3.0-alpha.5] 1.4.1
[Conner (Micha).pdf](https://github.com/elyukai/optolith-client/files/5303433/Conner.Micha.pdf)

**Comment by elyukai** [comment]
Oh, thats true, it doesnt do line breaks! 🙈 Thanks for the detailed bug report!! 🤗🤗🥰
