### ISSUE TITLE
Blinding Flash (Corebook Spell) - Wrong Improvement Cost

### ISSUE THREAD

**Issue by ZeSandman** [elyukai/optolith-client#736]
From DarthDQ on Discord

"Hey, I was just using Optolith (which if fantastic, by the way), but I think I noticed a bug, and I wasn't sure where to report it.  I was making a character and adding the spell, **Blinding Flash.  Optolith has the Improvement Cost listed as A, but in the book, it lists the Improvement Cost as B.**  When I was making my character, it was not taking off the correct amount of AP."

I comfirmed this

Improvement cost:
Core Book : B
Optolith: A

**Comment by elyukai** [comment]
Just to complete this issue based on Discord:

A is correct; B is a mistake and will be added to the English errata.
