### ISSUE TITLE
Auto-Update not working for Linux AppImage

### ISSUE THREAD

**Issue by pickbreaker** [elyukai/optolith-client#753]
Discord-Conversation mit @elyukai :

> pickbreaker heute um 21:40 Uhr
Bei mir ist der "Nach Updates Suchen"-Button in den Einstellungen ausgegraut. Ich bin auf Linux in der 1.4.0-alpha.15. Soll ich ein Github_issue dafür öffnen?

> elyukai heute um 21:40 Uhr
Hast du die tar.gz oder das AppImage?

> pickbreaker heute um 21:43 Uhr
das AppImage

> elyukai heute um 21:44 Uhr
hab ich das richtig verstanden dass das AppImage nicht von sich aus updaten kann sondern man dafür den AppImageUpdater oder wie der heißt braucht, der einen Update-Button über das Kontextmenü bereitstellt?

> pickbreaker heute um 21:47 Uhr
Bisher hat das Auto-Update immer funktioniert. Er hat mir nur seit der Version die Updates nicht mehr angeboten, deshalb wollte ich den Vorgang manuell auslösen, um herauszufinden wo das Problem liegt.

> elyukai heute um 21:49 Uhr
ich habe letztens mal geschaut, dass ich den updater nur dort aktiv habe, wo er auch potenziell funktioniert. Das ist aktuell Windows und AppImage auf Linux. Das Problem auf Linux ist, dass ich das Packaging-Format nicht abfragen kann. Und dann hatte ich halt gelesen, dass dieser AppImageUpdater das selbst macht.
Aber wenn das trotzdem ohne geht, dann ist das einfach ein Fehler von mir aus, weil ich es falsch verstanden hatte
dann muss ich nur schauen, wie ich es hinbekomme, dass das bei der tar.gz trotzdem ausgeblendet wird. uff ...

> pickbreaker heute um 21:49 Uhr
Ich werde also einfach manuell upgraden

> elyukai heute um 21:50 Uhr
ich baue das wieder zurück :see_no_evil:
tut mir leid :/

> pickbreaker heute um 21:50 Uhr
Wollte nur, dass das Problem bekannt ist
Kein Problem, schlag dich erstmal mit den wichtigeren Sachen herum als damit. Die Menüverknüpfung muss ich sowieso immer manuell updaten, dann kann ich auch den Optolith manuell aktualisieren.

> elyukai heute um 21:55 Uhr
danke fürs melden :see_no_evil:
wenn du einen issue erstellen möchtest, kannst du das sehr gerne machen, ansonsten erstelle ich einen :see_no_evil:

**Comment by FloraMayr** [comment]
`(OptolithInsider:3115): Gtk-WARNING **: 19:50:20.309: Theme parsing error: gtk.css:4419:85: '/*' in comment block

(OptolithInsider:3115): Gtk-WARNING **: 19:50:20.310: Theme parsing error: gtk.css:4512:64: '/*' in comment block
main: Set user data path ...
main: Install extensions ...
(node:3115) ExtensionLoadWarning: Warnings loading extension at /home/flora/.config/Optolith Insider/extensions/fmkadmapgofadopljbjfkapdkoienihi:
  Unrecognized manifest key 'browser_action'.
  Unrecognized manifest key 'minimum_chrome_version'.
  Unrecognized manifest key 'update_url'.
  Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.

(Use `OptolithInsider --trace-warnings ...` to show where the warning was created)
(node:3115) ExtensionLoadWarning: Warnings loading extension at /home/flora/.config/Optolith Insider/extensions/lmhkpmbekcpmknklioeibfkpmmfibljd:
  Unrecognized manifest key 'commands'.
  Unrecognized manifest key 'homepage_url'.
  Unrecognized manifest key 'page_action'.
  Unrecognized manifest key 'short_name'.
  Unrecognized manifest key 'update_url'.
  Permission 'notifications' is unknown or URL pattern is malformed.
  Permission 'contextMenus' is unknown or URL pattern is malformed.
  Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.

main: Installed extensions: Redux DevTools
main: Create Window ...
main (window): Initialize window state keeper
main (window): Initialize browser window
main (window): Manage browser window with state keeper
main (window): Load url
main (window): Show window
main (window): Maximize window ...
main: Updater is not available
`

Terminal output beim Starten der .AppImage, Version 1.5.0-Alpha.4 
OS: Xubuntu 20.4
