### ISSUE TITLE
Missing word in AMA3 "Schutz des Dolches"

### ISSUE THREAD

**Issue by Saphirius** [elyukai/optolith-client#774]
"Der Druide ritzt sich mit dem Dolch in die Handfläche und verliert dabei 1 LeP. Anschließend kann er für die nächsten 2 Stunden, wenn er durch die Elemente Feuer, Wasser, Luft, Erz, Eis und Humus TP/SP erleidet, beliebig viele W6 des Schadens einmal neu auswürfeln und das für ihn bessere Ergebnis der einzelnen Würfel wählen.(**Mit**) dem neuen Auswürfeln endet der Schutz und die Fähigkeit muss gegebenenfalls neu eingesetzt werden. Ob der elementare Schaden durch einen Zauber (z. B. Ignifaxius), ein Naturphänomen beispielsweise Steinschlag, Lawine, Hagel) oder Angriffe von Dämonen/Elementaren entsteht, ist dabei belanglos."
Das Wort "Mit" fehlt zu Beginn des 3. Satzes.

**Comment by elyukai** [comment]
It should be „Nach“ instead of „Mit“ (see [RegelWiki](https://dsa.ulisses-regelwiki.de/traditionsartefakt_sf_dolchritual.html?sonderfertigkeit=Schutz+des+Dolches))
