### ISSUE TITLE
Not all items are select-/buyable

### ISSUE THREAD

**Issue by JonasTrampe** [elyukai/optolith-client#791]
**Describe the bug**
Not all items are availible that exists as a template but do not have prerequisites.
E.g. the travel anvil should not have any dependencies as a buyable tool.
But it is neither availible in the character creation nor on the build character.
But it is availible as a template. 

**To Reproduce**
Load a char (finished or unfinished) go to possesions/Besitz.
Search for anvil or amboss or travel or reise an add/hizufügen.
Find nothing.

Click on create - open the template to copy from. Search for the item.
Find it. 
This seems to be true for many other items as the list in add is significantly shorter than the template stuff. eg travel chest.

**Expected behavior**
Items should not need to be copied from a template but be availible on creation.

**Screenshots**
![item_add](https://user-images.githubusercontent.com/37023459/99118018-0f5f8480-25f7-11eb-81a4-8b91c28046d3.png)
![item_create](https://user-images.githubusercontent.com/37023459/99118019-0ff81b00-25f7-11eb-84bd-33d7e401300c.png)

**Environment (please complete the following information):**

- OS: Windows 10 64bit 1904.1 (should update it...)
- Version: 1.4.2

**Additional context**
-

**Comment by elyukai** [comment]
Thanks for the bug report!! 🤗🥰

Indeed, they should be available just as any other item. I'm gonna fix this! ✌🏻

**Comment by elyukai** [comment]
Already works in current development version! 🥳
