### ISSUE TITLE
Profession Garether Krieger is missing Swords 12

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#792]
&mdash; via email

- Swords 12 missing
- Orienting should be 3 instead of 2

**Comment by Lhiuvian** [comment]
@elyukai hier ist es vorhanden
![Kriegerin](https://user-images.githubusercontent.com/78608253/112242319-e2c61400-8c4b-11eb-9513-dfa482d5e912.png)

**Comment by Lhiuvian** [comment]
@elyukai auch Orientierung ist bei der Beta Version zu niedrig 2 (sollte aber 3 sein)
![Kriegerin1](https://user-images.githubusercontent.com/78608253/112242966-06d62500-8c4d-11eb-809c-97fd51a24281.png)
![Kriegerin2](https://user-images.githubusercontent.com/78608253/112242972-089fe880-8c4d-11eb-9743-521ea7d71ac1.png)
![Kriegerin3](https://user-images.githubusercontent.com/78608253/112242978-0a69ac00-8c4d-11eb-9f6b-d90d81568a72.png)
