### ISSUE TITLE
An item's primary attribute does not change in UI but on character sheet

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#798]
> Ich wollte unter Gegenstand bearbeiten die Leiteigenschaft auf KK ändern, aber es bleibt konstant bei GE/KK. Der Bogen zeigt es aber korrekt an.

— **Tsafried** on Discord

**Comment by Pepelios** [comment]
Scheinbar wir im Gegenstandseditor der Eintrag angezeigt, je nach Waffengattungs-Default Wert.
