### ISSUE TITLE
Schlachtermesser and Fleischerbeil are not marked improvised

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#808]
> Schlachtermesser und Fleischerbeil sind nicht als improvisierte Waffen gelistet.

— **Tsafried** on Discord

**Comment by Pepelios** [comment]
Fleischerbeil wird im Heldenbogen angezeigt.  Schlachtermesser wird nicht angezeigt, weil keine Schadensschwelle eingetragen ist. Offenbar werden nur improvisierte Waffen eingetragen, die eine Schadensschwelle haben. Für das Schlachtermesser gibt es aber keine Schadensschwelle.
=> Vorschlag: Wenn keine Schadensschwelle eingetragen ist, die Berechnung im Heldenbogen ohne Schadenschwelle machen.
P.S.: Vermutung wieso Fleischerbeil beim Reporter ebenso nicht angezeigt wurde, hat mit der Reihenfolge der Gegenstände zu tun.

**Comment by Pepelios** [comment]
Aus der DSA Redaktion: L+S für das Schlachtermesser ist GE 14.
Ich mache morgen die Code Änderungen
