### ISSUE TITLE
Falsche Kosten für Kulturpaket "Bornländer"

### ISSUE THREAD

**Issue by WolfgangHG** [elyukai/optolith-client#824]
Das Kulturpaket "Bornländer" scheint mit falschen Kosten verrechnet zu werden.

Erfahrungsgrad "Kompetent", Rasse Mensch (0 AP), Kultur "Bornländer" ohne Auswahl des Kulturpakets (0 AP), Profession "Streuner/Spitzel" (228 AP):  Optolith zeigt restliche AP 972 an => OK.

Erfahrungsgrad "Kompetent", Rasse Mensch, Kultur "Bornländer" mit Auswahl des Kulturpakets (18 AP), Profession "Streuner/Spitzel":  restliche AP: **Optolith zeigt 953 statt 954 an**.

Das Kulturpaket setzt sich so zusammen (Regelwerk, S. 99):
Fährtensuchen +1 (3 AP), Holzbearbeitung +2 (4 AP), Lebensmittelbearbeitung +1 (1 AP), Orientierung +1 (2 AP),
Pflanzenkunde +1 (3 AP), Wildnisleben +1 (3 AP), Zechen +2 (2 AP)
==>Hier komme ich in der Summe also auch auf 18 AP.

**Comment by elyukai** [comment]
Danke für die Fehlermeldung! 🤗🥰

Die falschen Kosten liegen wahrscheinlich aber eher an einem falsch eingetragenen Wert. Sobald die SKP auf den Helden "angewendet" werden, werden nicht mehr die starren Werte verwendet, sondern es wird alles manuell zusammengerechnet.

Bei einer Differenz von einem AP wird es aber wahrscheinlich lustig, den Fehler zu finden, bzw. ob das wirklich ein Fehler im Professionspaketwert ist oder tatsächlich falsch hinterlegte Kosten eines einzelnen Eintrags. 🙃

**Comment by WolfgangHG** [comment]
Habe die Ursache gefunden: statt "Lederbearbeitung" (B) gehört Lebensmittelbearbeitung (A) ins Paket. Siehe Screenshot.
![kulturpaket_bornlaender](https://user-images.githubusercontent.com/138049/101982909-71072300-3c77-11eb-95f1-e757af954fcd.png)

**Comment by elyukai** [comment]
Oh, wow, vielen Dank fürs Nachsehen!! 🤗🤗🥰
