### ISSUE TITLE
Fehlermeldung: Fehler beim Speichern (Fehlercode: {"errno":-4048,"code":"EPERM","syscall":"open","path":

### ISSUE THREAD

**Issue by Battleschelm** [elyukai/optolith-client#829]
Ich habe mir heute 31.12.2020 Optolith heruntergeladen und nach dem speichern des Charakterbogens in der App, wollte ich den als PDF auf meinen Rechner speichern.

Egal wo ich das PDF speichern will, bekomme ich diese Fehlermeldung: 

Fehler beim Speichern (Fehlercode: {"errno":-4048,"code":"EPERM","syscall":"open","path":"C:\\***\\***\\***\\Yulag Yarum.pdf"})

**Comment by Battleschelm** [comment]
Ich konnte jetzt den Bogen als PDF speichern.

**Comment by elyukai** [comment]
Hi!

Vielen Dank für deine Meldung und damit auch Entschuldigung, dass ich mich erst jetzt bei dir melde! 😭😔

Letztendlich hätte ich dir aber wahrscheinlich auch nicht wirklich helfen können, daher freue ich mich, dass du selbst eine Lösung gefunden hast. Da ein Fehler durch fehlende Berechtigungen bisher nur aufgetreten ist, wenn man eine gerade geöffnete PDF-Datei überschreibt, wäre ich auch davon ausgegangen, dass es an deinem System liegt.

Wenn du noch mehr Probleme oder Feedback hast, erstelle gerne neue Issues; ich freue mich über jede Form von Feedback! 🤗☺️
