### ISSUE TITLE
Eigene Zauber/Liturgien/Magische Handlungen

### ISSUE THREAD

**Issue by RondraLion** [elyukai/optolith-client#830]
Hallo wäre es möglich ganz wie bei den Eigenen Sonderfertigkeiten auch eigene Zauber usw. Einfügen zu können.

**Comment by elyukai** [comment]
Hallo! 👋🏻 

Es wäre möglich, ja, ist aber recht aufwändig und daher kurzfristig nicht geplant bzw. möglich. Bei V/N/SFs ging es nur als Zwischenlösung, weil deren normale Architektur dies in diesem sehr begrenzten Rahmen ermöglicht; das ist bei Zaubern etc. so nicht der Fall.

Das Feature ist bereits in #28 getrackt, daher werde ich diesen Issue der Übersicht wegen schließen. 🙈
