### ISSUE TITLE
Strength value of 8 does not allow me to raise combat technique over 6

### ISSUE THREAD

**Issue by JoveToo** [elyukai/optolith-client#835]
**Describe the bug**
If my Strength is 8, I cannot raise it over 6 (the default).
If my Strength is 9, I can raise it to 11, which seems correct.

**To Reproduce**

Set a Strength value of 8.
Try to increase Combat Technique rating.

**Expected behavior**
I expect the Strength rating to be able to raise to 10.

**Environment (please complete the following information):**

Linux, 1.4.2

**Comment by pickbreaker** [comment]
might be related to #266
