### ISSUE TITLE
Character without disadvantages has black square in character sheet

### ISSUE THREAD

**Issue by JoveToo** [elyukai/optolith-client#840]
**Describe the bug**
If you create a character without any disadvantages and you generate the character sheet, it has a huge black square in place of the disadvantages.

**To Reproduce**
Create character without disadvantage. 

**Expected behavior**
Empty place, not black square

**Screenshots**

**Environment (please complete the following information):**

Linux, 1.4.2

**Comment by JoveToo** [comment]
![Screenshot from 2021-01-26 20-05-47](https://user-images.githubusercontent.com/18113628/106031911-1bc08d00-60d0-11eb-9439-4e6bc151570c.png)

**Comment by elyukai** [comment]
Can you reproduce the bug in the current 1.5.0-alpha.7 prerelease?

**Comment by elyukai** [comment]
Closing this bug for now, please reopen if this still applies.
