### ISSUE TITLE
Spell "Zauberschnurren" has typo in effect.

### ISSUE THREAD

**Issue by Zakant** [elyukai/optolith-client#846]
**Describe the bug**
In the german version the spell "Zauberschnurren" has mixed up the QS in the effect.
QS 2 and three are swapped (only the numbers, not the effect itself)

**To Reproduce**
n/a

**Expected behavior**
n/a

**Screenshots**
![grafik](https://user-images.githubusercontent.com/6419974/106250299-bd042c00-6213-11eb-840b-60c3148c8c60.png)

**Environment (please complete the following information):**

- OS: Windows 10
- Version: 1.4.2 (current stable and insider)

**Comment by Pepelios** [comment]
This will be handled within #1122 
I close this to avoid duplicates.
