### ISSUE TITLE
Fehlender "Nachteil" in AGÖII

### ISSUE THREAD

**Issue by Saphirius** [elyukai/optolith-client#852]
- Book: [Aveturisches Götterwirken II]
- Printing: [Ich glaube 1.]
- Page(s): [27]
- Area: [Die Tradition (Hesindekirche) als Sonderfertigkei]

**Describe the bug**
Ein Hesindegeweihter muss sich an den Moralkodex (Prinzipientreue) halten (siehe links). Die
Wahl des Nachteils ist Voraussetzung, wenn der Spieler einen Geweihten der Kirche spielen will.

**Expected text**
Ein Hesindegeweihter muss sich an den Moralkodex (Prinzipientreue) halten (siehe links). Die
Wahl des Nachteils ("Neugierig") ist Voraussetzung, wenn der Spieler einen Geweihten der Kirche spielen will.

**Optolith Version:**
/

**Additional context**
Ich weiß nicht genau welcher Nachteil, aber Neugierig macht vom Fluff her Sinn.

**Comment by elyukai** [comment]
Vielen Dank für deine Meldung! 🤗 Ich verstehe aber leider nicht ganz den Fehler … 🙈

Die SF *Tradition (Hesindekirche)* kommt im Regelwerk und in Aventurisches Götterwirken I vor; Aventurisches Götterwirken II ist noch nicht implementiert (siehe #406). Alle Traditionen müssen den Nachteil Prinzipientreue für den Moralkodex ihrer jeweiligen Gottheit kaufen, wenn sie die Tradition erlernen möchten. Das ist da mit "des Nachteils" gemeint; es bezieht sich auf den vorherigen Satz. Daher verstehe ich gerade leider nicht ganz, wieso noch ein zweiter Nachteil erforderlich ist … 🤔🙈
