### ISSUE TITLE
FLUX: Kampfstilsonderfertigkeiten

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#921]
**Sources**

- S. 7 (Kampfstilsonderfertigkeiten)

**Special Notes**

- Werden Waffen als Beschränkung bei Kampftechniken angegeben und neue Waffen können aufgrund des Fortschritts bei der Datenbanküberarbeitung noch nicht eingetragen werden, bitte `0` als ID der Waffe eintragen und per Kommentar (mit `#` ist alles danach in der Zeile ein Kommentar) den Namen der Waffe noch angeben.

**Special Implementations**

—

**Comment by pickbreaker** [comment]
Should be closed
