### ISSUE TITLE
GDG: Kulturen

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#946]
**Sources**

- S. 127–128 (Neue Kultur)

**Special Notes**

—

**Special Implementations**

—

**Comment by Jordok** [comment]
Kann erst nach Erstellung der AGÖ2 Professionen entgültig abgeschlossen werden, da bei der Kultur die Gjalsker Schamanenprofession als übliche geweihte Profession eingetragen werden muss.
