### ISSUE TITLE
G&K: Animistenkräfte

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#989]
**Sources**

- S. 9–12 (Animistenkräfte)

**Special Notes**

—

**Comment by panikpansen** [comment]
Drei Animistenkräfte sind mit zusätzlichen Informationen in Tabellenform gelistet, bei denen ich mir nicht sicher bin, wie die einzupflegen sind: SPELL_484 ("Mächtiger Patronruf") (G&K:10) listet für 14 Patrontiere AsP-Kosten und Steigerungsfaktoren; SPELL_486 ("Tierkräfte III") (G&K: 10-11) listet pro Patrontier separate Eigeschaftsboni; SPELL_461 ("Tierverwandlung") (G&K: 11) listet einen überarbeiteten Regeltext und referenziert nicht mehr den Zauber Adlerschwinge, sondern neue AsP-Kosten und Steigerungsfaktoren pro Patrontier.
